//! Optimization and transformation passes for the Solar compiler.

mod adce;
mod cfg_simplify;
mod check_elim;
mod cse;
mod dce;
mod frame_promotion;
mod gvn;
mod indvar_simplify;
mod inline;
mod inst_simplify;
mod jump_threading;
mod load_pre;
mod loop_canonicalize;
mod loop_opt;
mod lower_abi;
pub(crate) mod lower_abi_encode;
mod lower_alloc;
mod lower_dispatch;
mod lower_evm_shaped;
mod lower_mapping_slots;
mod lower_slices;
mod memory_dse;
mod outline_reverts;
mod pre;
mod pure_eval;
mod sccp;
mod static_alloc;
mod storage_dse;
mod storage_load_cse;
mod storage_promotion;
mod utils;

pub(crate) use adce::AdcePass;
pub(crate) use cfg_simplify::{CfgSimplifyPass, FunctionDcePass};
pub(crate) use check_elim::CheckElimPass;
pub(crate) use cse::CsePass;
pub(crate) use dce::{DcePass, DeadCodeEliminator};
pub(crate) use frame_promotion::FrameSlotPromotionPass;
pub(crate) use gvn::GvnPass;
pub(crate) use indvar_simplify::IndVarSimplifyPass;
pub(crate) use inline::InlinePass;
pub(crate) use inst_simplify::InstSimplifyPass;
pub(crate) use jump_threading::JumpThreadingPass;
pub(crate) use load_pre::LoadPrePass;
pub(crate) use loop_canonicalize::LoopCanonicalizePass;
pub(crate) use loop_opt::LicmPass;
pub(crate) use lower_abi::LowerAbiPass;
pub(crate) use lower_abi_encode::LowerAbiEncodePass;
pub(crate) use lower_dispatch::LowerDispatchPass;
pub(crate) use lower_evm_shaped::LowerEvmShapedPass;
pub(crate) use lower_mapping_slots::LowerMappingSlotsPass;
pub(crate) use lower_alloc::LowerAllocPass;
pub(crate) use lower_slices::LowerSlicesPass;
pub(crate) use memory_dse::MemoryDsePass;
pub(crate) use outline_reverts::OutlineRevertsPass;
pub(crate) use pre::PrePass;
pub(crate) use pure_eval::PureEvalPass;
pub(crate) use sccp::SccpTransformPass;
pub(crate) use static_alloc::StaticAllocPass;
pub(crate) use storage_dse::StorageDsePass;
pub(crate) use storage_load_cse::StorageLoadCsePass;
pub(crate) use storage_promotion::StorageScalarPromotionPass;

pub(crate) use lower_alloc::lower_alloc_except;
pub(crate) use static_alloc::eligible_static_allocations;
pub(crate) use utils::{DispatchCallvalue, rejects_callvalue};
