[files]
extend-exclude = [
    ".git",
    "target",
    "testdata",
    "Cargo.toml",
    "Cargo.lock",
    "CHANGELOG.md",
    "*.json",
    "**/tests/**",
    "**/test/**",
    "**/*_test.*",
    "**/*_tests.*",
    "crates/parse/src/lexer/unicode_chars.rs", # Weird words.
    "dist-workspace.toml",
]

[default]
# Abbreviated commit hashes such as `ba539e44a`.
extend-ignore-re = ["\\b[0-9a-f]{9}\\b"]

[default.extend-identifiers]
numLits = "numLits"
unitLits = "unitLits"

[default.extend-words]
ket = "ket"
Mke = "Mke"
numer = "numer"
Pn = "Pn"
typ = "typ"
