[files]
extend-exclude = [
    ".git",
    "target",
    "testdata",
    "Cargo.toml",
    "Cargo.lock",
    "CHANGELOG.md",
    "*.json",
    "**/tests/**",
    "**/test/**",
    "**/*_test.*",
    "**/*_tests.*",
    "crates/parse/src/lexer/unicode_chars.rs", # Weird words.
    "dist-workspace.toml",
    "crates/lsp/src/global_state.rs", # External crate uses the word "typ" in place of "ty".
]

[default.extend-words]
ket = "ket"
numer = "numer"
