//! Contract bytecode generation and dependency orchestration.

use crate::{
    Backend, EvmCodegen,
    backend::evm::ir,
    lower::{self, contract_bytecode_dependencies},
};
use alloy_primitives::Bytes;
use either::Either;
use solar_data_structures::{bit_set::DenseBitSet, map::FxHashMap};
use solar_interface::Result;
use solar_sema::{Gcx, hir::ContractId};

/// Generated bytecode and optional final EVM IR for one contract.
#[derive(Clone, Debug, Default)]
pub struct ContractArtifact {
    /// Deployment bytecode.
    pub deployment: Bytes,
    /// Runtime bytecode.
    pub runtime: Bytes,
    /// Final deployment-prefix EVM IR immediately before byte emission.
    pub deployment_evm_ir: Option<ir::Module>,
    /// Final runtime EVM IR immediately before byte emission.
    pub runtime_evm_ir: Option<ir::Module>,
}

/// A contract selection.
#[derive(Clone, Copy, Debug)]
pub enum ContractSelection<T> {
    /// Generate only the listed contracts and their dependencies.
    Specific(T),
    /// Generate every deployable contract.
    All,
}

impl<T> ContractSelection<T>
where
    T: IntoIterator<Item = ContractId>,
{
    /// Returns the specific contracts or every deployable contract.
    pub fn into_iter<'gcx>(
        self,
        gcx: Gcx<'gcx>,
    ) -> impl Iterator<Item = ContractId> + use<'gcx, T> {
        match self {
            Self::Specific(contracts) => Either::Left(contracts.into_iter()),
            Self::All => Either::Right(gcx.hir.contract_ids().filter(move |&contract_id| {
                let contract = gcx.hir.contract(contract_id);
                !contract.kind.is_interface() && !contract.kind.is_abstract_contract()
            })),
        }
    }
}

/// Generates bytecode for selected contracts and their creation-bytecode dependencies.
///
/// Contracts in `capture_evm_ir` retain their final EVM IR in the returned artifact.
pub fn generate_contract_bytecodes<T, U>(
    gcx: Gcx<'_>,
    contracts: ContractSelection<T>,
    capture_evm_ir: ContractSelection<U>,
) -> Result<FxHashMap<ContractId, ContractArtifact>>
where
    T: IntoIterator<Item = ContractId>,
    U: IntoIterator<Item = ContractId>,
{
    let mut capture_evm_ir_set = DenseBitSet::new_empty(gcx.hir.contract_ids().len());
    let capture_all_evm_ir = match capture_evm_ir {
        ContractSelection::Specific(contracts) => {
            for contract_id in contracts {
                capture_evm_ir_set.insert(contract_id);
            }
            false
        }
        ContractSelection::All => true,
    };

    let mut artifacts = FxHashMap::default();
    let mut visiting = DenseBitSet::new_empty(gcx.hir.contract_ids().len());
    for contract_id in contracts.into_iter(gcx) {
        ensure_contract_bytecode(
            gcx,
            contract_id,
            capture_all_evm_ir,
            &capture_evm_ir_set,
            &mut artifacts,
            &mut visiting,
        )?;
    }
    Ok(artifacts)
}

fn ensure_contract_bytecode(
    gcx: Gcx<'_>,
    contract_id: ContractId,
    capture_all_evm_ir: bool,
    capture_evm_ir: &DenseBitSet<ContractId>,
    artifacts: &mut FxHashMap<ContractId, ContractArtifact>,
    visiting: &mut DenseBitSet<ContractId>,
) -> Result {
    if artifacts.contains_key(&contract_id) {
        return Ok(());
    }

    let contract = gcx.hir.contract(contract_id);
    if contract.kind.is_interface() || contract.kind.is_abstract_contract() {
        return Err(gcx
            .dcx()
            .err("cannot generate creation bytecode for non-deployable contract")
            .span(contract.span)
            .emit());
    }

    if !visiting.insert(contract_id) {
        return Err(gcx
            .dcx()
            .err("recursive contract creation bytecode dependency")
            .span(contract.span)
            .emit());
    }

    let dependencies = contract_bytecode_dependencies(gcx, contract_id);
    for dependency in &dependencies {
        ensure_contract_bytecode(
            gcx,
            dependency,
            capture_all_evm_ir,
            capture_evm_ir,
            artifacts,
            visiting,
        )?;
    }

    let child_bytecodes = dependencies
        .iter()
        .map(|dependency| {
            let bytecode = artifacts
                .get(&dependency)
                .expect("dependency artifact should have been generated")
                .deployment
                .clone();
            (dependency, bytecode)
        })
        .collect();
    let mut module = lower::lower_contract_with_bytecodes(gcx, contract_id, &child_bytecodes);
    gcx.dcx().has_errors()?;

    let mut codegen = EvmCodegen::new(gcx);
    codegen.set_capture_evm_ir(capture_all_evm_ir || capture_evm_ir.contains(contract_id));
    let artifact = codegen.lower_module(&mut module);
    gcx.dcx().has_errors()?;

    artifacts.insert(
        contract_id,
        ContractArtifact {
            deployment: artifact.deployment.into(),
            runtime: artifact.runtime.into(),
            deployment_evm_ir: artifact.deployment_evm_ir,
            runtime_evm_ir: artifact.runtime_evm_ir,
        },
    );
    visiting.remove(contract_id);

    Ok(())
}
