//! Contract bytecode generation and dependency orchestration.

use crate::{
    Backend, EvmCodegen,
    backend::evm::{self, DebugInstruction, ir},
    lower,
    mir::{LibraryLink, Module},
    pass::run_pipeline,
};
use alloy_primitives::Bytes;
use either::Either;
use solar_ast::TypeSize;
use solar_config::{EvmVersion, OptimizationMode};
use solar_data_structures::{
    bit_set::{DenseBitSet, GrowableBitSet},
    index::IndexVec,
    map::FxHashMap,
    sync::{self, Scope},
};
use solar_interface::{Result, error_code};
use solar_sema::{
    Gcx,
    hir::{ContractId, VariableId},
};
use std::sync::{
    OnceLock,
    atomic::{AtomicUsize, Ordering},
};

/// Generated bytecode and optional intermediate representations for one contract.
#[derive(Clone, Debug, Default)]
pub struct ContractArtifact {
    /// Deployment bytecode.
    pub deployment: Bytes,
    /// Runtime bytecode.
    pub runtime: Bytes,
    /// Immutable placeholders in the runtime bytecode.
    pub immutable_references: Vec<ImmutableReference>,
    /// Unresolved library addresses in the deployment bytecode.
    pub deployment_link_references: Vec<LibraryReference>,
    /// Unresolved library addresses in the runtime bytecode.
    pub runtime_link_references: Vec<LibraryReference>,
    /// Library placeholders this artifact may contain, including those of every contract
    /// whose creation or runtime code it embeds.
    pub(crate) library_links: Vec<LibraryLink>,
    /// Captured MIR, built under `-O none` when no explicit pipeline is configured and
    /// post-pipeline otherwise.
    pub mir: Option<Module>,
    /// Final deployment-prefix EVM IR immediately before byte emission.
    pub deployment_evm_ir: Option<ir::Module>,
    /// Final runtime EVM IR immediately before byte emission.
    pub runtime_evm_ir: Option<ir::Module>,
    /// Final deployment-prefix instruction locations.
    pub deployment_debug_info: Option<Vec<DebugInstruction>>,
    /// Final runtime instruction locations.
    pub runtime_debug_info: Option<Vec<DebugInstruction>>,
}

/// An immutable placeholder in runtime bytecode.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ImmutableReference {
    /// Source variable containing the immutable declaration.
    ///
    /// `None` for a library's own deployment address, which guards its non-view functions
    /// against direct calls and is reported as [`Self::LIBRARY_DEPLOY_ADDRESS`], like solc's
    /// IR pipeline.
    pub variable_id: Option<VariableId>,
    /// Byte offset where the placeholder data begins.
    pub start: usize,
    /// Type width encoded by the placeholder.
    pub type_size: TypeSize,
}

impl ImmutableReference {
    /// The `immutableReferences` key of a library's own deployment address placeholder.
    pub const LIBRARY_DEPLOY_ADDRESS: &str = "library_deploy_address";
}

/// An unresolved library address in generated bytecode.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LibraryReference {
    /// Source unit containing the library.
    pub source: String,
    /// Library contract name.
    pub name: String,
    /// Byte offset where the address begins.
    pub start: usize,
}

/// Returns opaque data to emit at the end of a contract's runtime program.
pub type RuntimeDataFn<'a> = dyn Fn(ContractId) -> Bytes + Sync + 'a;

/// A contract selection.
#[derive(Clone, Debug)]
pub enum ContractSelection {
    /// Generate only the listed contracts and their dependencies.
    Specific(DenseBitSet<ContractId>),
    /// Generate every deployable contract.
    All,
}

impl ContractSelection {
    /// Creates an empty contract selection.
    pub fn empty(gcx: Gcx<'_>) -> Self {
        Self::Specific(DenseBitSet::new_empty(gcx.hir.contract_ids().len()))
    }

    /// Returns the specific contracts or every deployable contract.
    pub fn into_iter<'a, 'gcx>(
        &'a self,
        gcx: Gcx<'gcx>,
    ) -> impl Iterator<Item = ContractId> + use<'a, 'gcx> {
        match self {
            Self::Specific(contracts) => Either::Left(contracts.iter()),
            Self::All => Either::Right(gcx.hir.contract_ids().filter(move |&contract_id| {
                let contract = gcx.hir.contract(contract_id);
                !contract.kind.is_interface() && !contract.kind.is_abstract_contract()
            })),
        }
    }

    /// Adds another selection to this one.
    pub fn union_with(&mut self, other: &Self) {
        match other {
            Self::Specific(other) => {
                if let Self::Specific(contracts) = self {
                    contracts.union(other);
                }
            }
            Self::All => *self = Self::All,
        }
    }

    /// Selects `contract_id`.
    pub fn insert(&mut self, contract_id: ContractId) {
        if let Self::Specific(contracts) = self {
            contracts.insert(contract_id);
        }
    }

    /// Returns whether no contracts are selected.
    pub fn is_empty(&self) -> bool {
        matches!(self, Self::Specific(contracts) if contracts.is_empty())
    }

    /// Returns whether `contract_id` is selected.
    fn contains(&self, contract_id: ContractId) -> bool {
        match self {
            Self::Specific(contracts) => contracts.contains(contract_id),
            Self::All => true,
        }
    }
}

/// Generates requested contract artifacts and their creation-bytecode dependencies.
///
/// Contracts in `contracts` retain bytecode in the returned artifact.
/// Contracts in `capture_mir` retain built MIR under `-O none` when no explicit pipeline is
/// configured and final MIR otherwise.
/// Contracts in `capture_evm_ir` retain their final EVM IR in the returned artifact.
/// Values returned by `runtime_data` are emitted as trailing runtime program data.
/// Contracts in `capture_debug_info` retain final instruction locations.
pub fn generate_contract_bytecodes(
    gcx: Gcx<'_>,
    contracts: &ContractSelection,
    capture_mir: &ContractSelection,
    capture_evm_ir: &ContractSelection,
    runtime_data: Option<&RuntimeDataFn<'_>>,
    capture_debug_info: &ContractSelection,
) -> Result<FxHashMap<ContractId, ContractArtifact>> {
    let captures = ContractCaptures {
        bytecode: contracts,
        mir: capture_mir,
        evm_ir: capture_evm_ir,
        runtime_data,
        debug_info: capture_debug_info,
        // Snapshot this once, before any contract is lowered: a report emitted
        // by one contract's lowering must not silence another's.
        sema_errored: gcx.dcx().has_errors().is_err(),
    };
    let mut requested = contracts.clone();
    requested.union_with(capture_mir);
    requested.union_with(capture_evm_ir);
    requested.union_with(capture_debug_info);
    let graph = ContractGraph::discover(gcx, &requested)?;
    let contract_count = gcx.hir.contract_ids().len();
    let artifacts =
        IndexVec::<ContractId, _>::from_vec((0..contract_count).map(|_| OnceLock::new()).collect());
    let remaining_dependencies = IndexVec::<ContractId, _>::from_vec(
        graph
            .dependencies
            .iter()
            .map(|dependencies| AtomicUsize::new(dependencies.len()))
            .collect(),
    );

    let mut ready = DenseBitSet::new_empty(contract_count);
    for contract_id in graph.reachable.iter() {
        if graph.dependencies[contract_id].is_empty() {
            ready.insert(contract_id);
        }
    }

    // Pass debugging writes directly to stdout and stderr, so keep its output ordered.
    let parallel = gcx.sess.is_parallel()
        && !gcx.sess.opts.unstable.print_after_each
        && !gcx.sess.opts.unstable.pass_diff
        && !gcx.sess.opts.unstable.time_passes;
    sync::scope(parallel, |scope| {
        for contract_id in ready.iter() {
            spawn_contract_codegen(
                &scope,
                gcx,
                captures,
                &graph,
                &artifacts,
                &remaining_dependencies,
                contract_id,
            );
        }
    });
    gcx.dcx().has_errors()?;

    let mut generated = FxHashMap::default();
    for (contract_id, artifact) in artifacts.into_iter_enumerated() {
        if graph.reachable.contains(contract_id) {
            generated.insert(
                contract_id,
                artifact.into_inner().expect("contract artifact should have been generated"),
            );
        }
    }
    Ok(generated)
}

#[derive(Clone, Copy)]
struct ContractCaptures<'a> {
    bytecode: &'a ContractSelection,
    mir: &'a ContractSelection,
    evm_ir: &'a ContractSelection,
    runtime_data: Option<&'a RuntimeDataFn<'a>>,
    debug_info: &'a ContractSelection,
    /// Whether the compilation had already failed when this phase started.
    sema_errored: bool,
}

struct ContractGraph {
    dependencies: IndexVec<ContractId, GrowableBitSet<ContractId>>,
    dependents: IndexVec<ContractId, Vec<ContractId>>,
    reachable: DenseBitSet<ContractId>,
}

impl ContractGraph {
    fn discover(gcx: Gcx<'_>, contracts: &ContractSelection) -> Result<Self> {
        let contract_count = gcx.hir.contract_ids().len();
        let mut graph = Self {
            dependencies: IndexVec::from_vec(
                (0..contract_count).map(|_| GrowableBitSet::new_empty()).collect(),
            ),
            dependents: IndexVec::from_vec((0..contract_count).map(|_| Vec::new()).collect()),
            reachable: DenseBitSet::new_empty(contract_count),
        };
        let mut visiting = DenseBitSet::new_empty(contract_count);
        for contract_id in contracts.into_iter(gcx) {
            graph.discover_contract(gcx, contract_id, &mut visiting)?;
        }
        Ok(graph)
    }

    fn discover_contract(
        &mut self,
        gcx: Gcx<'_>,
        contract_id: ContractId,
        visiting: &mut DenseBitSet<ContractId>,
    ) -> Result {
        if self.reachable.contains(contract_id) {
            return Ok(());
        }

        let contract = gcx.hir.contract(contract_id);
        if contract.kind.is_interface() || contract.kind.is_abstract_contract() {
            return Err(gcx
                .dcx()
                .err("cannot generate creation bytecode for non-deployable contract")
                .span(contract.span)
                .emit());
        }

        if !visiting.insert(contract_id) {
            return Err(gcx
                .dcx()
                .err("recursive contract creation bytecode dependency")
                .span(contract.span)
                .emit());
        }

        let dependencies = gcx.contract_bytecode_dependencies(contract_id);
        for dependency in dependencies.iter() {
            self.dependents[dependency].push(contract_id);
            self.discover_contract(gcx, dependency, visiting)?;
        }
        for dependency in dependencies.iter() {
            self.dependencies[contract_id].insert(dependency);
        }
        self.reachable.insert(contract_id);
        visiting.remove(contract_id);
        Ok(())
    }
}

fn spawn_contract_codegen<'scope, 'gcx>(
    scope: &Scope<'_, 'scope>,
    gcx: Gcx<'gcx>,
    captures: ContractCaptures<'scope>,
    graph: &'scope ContractGraph,
    artifacts: &'scope IndexVec<ContractId, OnceLock<ContractArtifact>>,
    remaining_dependencies: &'scope IndexVec<ContractId, AtomicUsize>,
    contract_id: ContractId,
) where
    'gcx: 'scope,
{
    scope.spawn(move |scope| {
        let Ok(artifact) = generate_contract_bytecode(gcx, contract_id, captures, graph, artifacts)
        else {
            return;
        };
        artifacts[contract_id]
            .set(artifact)
            .expect("contract artifact should only be generated once");

        for &dependent in &graph.dependents[contract_id] {
            let previous = remaining_dependencies[dependent].fetch_sub(1, Ordering::AcqRel);
            assert!(previous > 0, "contract dependency count underflow");
            if previous == 1 {
                spawn_contract_codegen(
                    &scope,
                    gcx,
                    captures,
                    graph,
                    artifacts,
                    remaining_dependencies,
                    dependent,
                );
            }
        }
    });
}

fn generate_contract_bytecode(
    gcx: Gcx<'_>,
    contract_id: ContractId,
    captures: ContractCaptures<'_>,
    graph: &ContractGraph,
    artifacts: &IndexVec<ContractId, OnceLock<ContractArtifact>>,
) -> Result<ContractArtifact> {
    let child_bytecodes = graph.dependencies[contract_id]
        .iter()
        .map(|dependency| {
            let artifact = artifacts[dependency]
                .get()
                .expect("dependency artifact should have been generated");
            (
                dependency,
                lower::ContractBytecodes::new(
                    artifact.deployment.clone(),
                    artifact.runtime.clone(),
                ),
            )
        })
        .collect();
    let mut module =
        lower::lower_contract(gcx, contract_id, &child_bytecodes, captures.sema_errored);
    gcx.dcx().has_errors()?;
    let capture_mir = captures.mir.contains(contract_id);
    let needs_backend = captures.bytecode.contains(contract_id)
        || captures.evm_ir.contains(contract_id)
        || captures.debug_info.contains(contract_id)
        || !graph.dependents[contract_id].is_empty();
    let runtime_data =
        captures.runtime_data.filter(|_| needs_backend).map(|data| data(contract_id));
    append_runtime_data(&mut module, runtime_data.as_ref());
    let capture_built = capture_mir
        && matches!(gcx.sess.opts.optimization, OptimizationMode::None)
        && gcx.sess.opts.unstable.mir_pipeline.is_none();
    let built_mir = (capture_built && needs_backend).then(|| module.clone());
    let artifact = if needs_backend {
        module.set_debug_info_tracked(captures.debug_info.contains(contract_id));
        let mut codegen = EvmCodegen::new(gcx);
        codegen.set_capture_mir(capture_mir && !capture_built);
        codegen.set_capture_evm_ir(captures.evm_ir.contains(contract_id));
        codegen.set_capture_debug_info(captures.debug_info.contains(contract_id));
        let artifact = codegen.lower_module(&mut module);
        gcx.dcx().has_errors()?;
        artifact
    } else {
        if capture_mir && !capture_built {
            let _changed = run_pipeline(gcx, &mut module, None);
            gcx.dcx().has_errors()?;
        }
        Default::default()
    };
    if let Some(limit) = gcx.sess.opts.evm_version.runtime_code_size_limit()
        && artifact.runtime.len() > limit
    {
        let fork = if gcx.sess.opts.evm_version >= EvmVersion::Amsterdam {
            EvmVersion::Amsterdam
        } else {
            EvmVersion::SpuriousDragon
        };
        gcx.dcx()
            .warn(format!(
                "contract code size is {} bytes and exceeds {} bytes",
                artifact.runtime.len(),
                limit
            ))
            .code(error_code!(5574))
            .span(gcx.hir.contract(contract_id).span)
            .note(format!("the limit was introduced in {fork}"))
            .note("this contract may not be deployable on Mainnet")
            .help(
                "consider enabling the optimizer with a low runs value, turning off revert strings, or using libraries",
            )
            .emit();
    }
    if let Some(limit) = gcx.sess.opts.evm_version.initcode_size_limit()
        && artifact.deployment.len() > limit
    {
        let fork = if gcx.sess.opts.evm_version >= EvmVersion::Amsterdam {
            EvmVersion::Amsterdam
        } else {
            EvmVersion::Shanghai
        };
        gcx.dcx()
            .warn(format!(
                "contract initcode size is {} bytes and exceeds {} bytes",
                artifact.deployment.len(),
                limit
            ))
            .code(error_code!(3860))
            .span(gcx.hir.contract(contract_id).span)
            .note(format!("the limit was introduced in {fork}"))
            .note("this contract may not be deployable on Mainnet")
            .help(
                "consider enabling the optimizer with a low runs value, turning off revert strings, or using libraries",
            )
            .emit();
    }
    let immutable_references = artifact
        .immutable_references
        .iter()
        .map(|reference| ImmutableReference {
            variable_id: module.immutable(reference.id).variable_id,
            start: reference.code_offset + 1,
            type_size: reference.type_size,
        })
        .collect();
    // Embedded creation and runtime code carries the dependencies' placeholders verbatim, so
    // their links are part of this artifact's link surface too.
    let mut library_links = module.library_links().to_vec();
    for dependency in graph.dependencies[contract_id].iter() {
        let dependency =
            artifacts[dependency].get().expect("dependency artifact should have been generated");
        for link in &dependency.library_links {
            if !library_links.contains(link) {
                library_links.push(link.clone());
            }
        }
    }
    let deployment_link_references =
        collect_library_references(&artifact.deployment, &library_links);
    let runtime_link_references = collect_library_references(&artifact.runtime, &library_links);
    let mir = capture_mir.then(|| built_mir.unwrap_or(module));

    Ok(ContractArtifact {
        deployment: artifact.deployment.into(),
        runtime: artifact.runtime.into(),
        immutable_references,
        deployment_link_references,
        runtime_link_references,
        library_links,
        mir,
        deployment_evm_ir: artifact.deployment_evm_ir,
        runtime_evm_ir: artifact.runtime_evm_ir,
        deployment_debug_info: artifact.deployment_debug_info,
        runtime_debug_info: artifact.runtime_debug_info,
    })
}

/// Locates every instruction-aligned `PUSH20 <placeholder>` in the bytecode.
///
/// The placeholders stay in the artifact bytes: a dependent contract embeds this artifact
/// verbatim and must find them again in its own scan, and outputs print them in solc's textual
/// form rather than as a silently linked zero address.
fn collect_library_references(bytecode: &[u8], links: &[LibraryLink]) -> Vec<LibraryReference> {
    let mut references = Vec::new();
    let mut offset = 0;
    while let Some(&opcode) = bytecode.get(offset) {
        offset += 1;
        let push_width = if (evm::op::PUSH1..=evm::op::PUSH32).contains(&opcode) {
            usize::from(opcode - evm::op::PUSH1 + 1)
        } else {
            0
        };
        let Some(data) = bytecode.get(offset..offset.saturating_add(push_width)) else {
            break;
        };
        if opcode == evm::op::PUSH20
            && let Some(link) = links.iter().find(|link| data == link.placeholder)
        {
            references.push(LibraryReference {
                source: link.source.clone(),
                name: link.name.clone(),
                start: offset,
            });
        }
        offset += push_width;
    }
    references
}

fn append_runtime_data(module: &mut Module, data: Option<&Bytes>) {
    if let Some(data) = data.filter(|data| !data.is_empty()) {
        module.append_runtime_data(data.clone(), None);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn library_references_skip_push_data() {
        let link = LibraryLink {
            source: "source.sol".to_string(),
            name: "Library".to_string(),
            placeholder: [42; 20],
        };
        let mut bytecode = vec![evm::op::PUSH20 + 1, evm::op::PUSH20];
        bytecode.extend(link.placeholder);
        let start = bytecode.len() + 1;
        bytecode.push(evm::op::PUSH20);
        bytecode.extend(link.placeholder);

        assert_eq!(
            collect_library_references(&bytecode, &[link]),
            [LibraryReference {
                source: "source.sol".to_string(),
                name: "Library".to_string(),
                start,
            }]
        );
    }
}
