//! Contract bytecode generation and dependency orchestration.

use crate::{
    EvmCodegen,
    backend::evm::{DebugInfo, EvmArtifact, ir},
    link::{
        ContractBytecodes, EmbeddedBytecodes, LibraryRelocation, LibraryTable, QualifiedName,
        RelocatableBytecode,
    },
    mir::{Module, lower, pass::run_pipeline},
};
use alloy_primitives::Bytes;
use either::Either;
use solar_ast::TypeSize;
use solar_config::{EvmVersion, OptimizationMode};
use solar_data_structures::{
    bit_set::{DenseBitSet, GrowableBitSet},
    index::IndexVec,
    map::FxHashMap,
    sync::{self, Mutex, Scope},
};
use solar_interface::{Result, error_code};
use solar_sema::{
    Gcx,
    hir::{ContractId, VariableId},
};
use std::{
    cmp::Reverse,
    collections::BinaryHeap,
    sync::{
        OnceLock,
        atomic::{AtomicUsize, Ordering},
    },
};

/// Generated bytecode and optional intermediate representations for one contract.
#[derive(Clone, Debug, Default)]
pub struct ContractArtifact {
    /// Deployment bytecode.
    pub deployment: Bytes,
    /// Runtime bytecode.
    pub runtime: Bytes,
    /// Immutable placeholders in the runtime bytecode.
    pub immutable_references: Vec<ImmutableReference>,
    /// Unresolved library addresses in the deployment bytecode.
    pub deployment_link_references: Vec<LibraryReference>,
    /// Unresolved library addresses in the runtime bytecode.
    pub runtime_link_references: Vec<LibraryReference>,
    /// Captured MIR, built under `-O none` when no explicit pipeline is configured and
    /// post-pipeline otherwise.
    pub mir: Option<Module>,
    /// Final deployment-prefix EVM IR immediately before byte emission.
    pub deployment_evm_ir: Option<ir::Module>,
    /// Final runtime EVM IR immediately before byte emission.
    pub runtime_evm_ir: Option<ir::Module>,
    /// Final deployment-prefix instruction locations.
    pub deployment_debug_info: Option<DebugInfo>,
    /// Final runtime instruction locations.
    pub runtime_debug_info: Option<DebugInfo>,
}

/// An immutable placeholder in runtime bytecode.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ImmutableReference {
    /// Source variable containing the immutable declaration.
    ///
    /// `None` for a library's own deployment address, which guards its non-view functions
    /// against direct calls and is reported as [`Self::LIBRARY_DEPLOY_ADDRESS`], like solc's
    /// IR pipeline.
    pub variable_id: Option<VariableId>,
    /// Byte offset where the placeholder data begins.
    pub start: usize,
    /// Type width encoded by the placeholder.
    pub type_size: TypeSize,
}

impl ImmutableReference {
    /// The `immutableReferences` key of a library's own deployment address placeholder.
    pub const LIBRARY_DEPLOY_ADDRESS: &str = "library_deploy_address";
}

/// An unresolved library address in generated bytecode.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LibraryReference {
    /// The library's fully qualified name.
    pub library: QualifiedName,
    /// Byte offset where the address begins.
    pub start: usize,
}

/// Returns opaque data to emit at the end of a contract's runtime program.
pub type RuntimeDataFn<'a> = dyn Fn(ContractId) -> Bytes + Sync + 'a;

/// A contract selection.
#[derive(Clone, Debug)]
pub enum ContractSelection {
    /// Generate only the listed contracts and their dependencies.
    Specific(DenseBitSet<ContractId>),
    /// Generate every deployable contract.
    All,
}

impl ContractSelection {
    /// Creates an empty contract selection.
    pub fn empty(gcx: Gcx<'_>) -> Self {
        Self::Specific(DenseBitSet::new_empty(gcx.hir.contract_ids().len()))
    }

    /// Returns the specific contracts or every deployable contract.
    pub fn into_iter<'a, 'gcx>(
        &'a self,
        gcx: Gcx<'gcx>,
    ) -> impl Iterator<Item = ContractId> + use<'a, 'gcx> {
        match self {
            Self::Specific(contracts) => Either::Left(contracts.iter()),
            Self::All => Either::Right(gcx.hir.contract_ids().filter(move |&contract_id| {
                let contract = gcx.hir.contract(contract_id);
                !contract.kind.is_interface() && !contract.kind.is_abstract_contract()
            })),
        }
    }

    /// Adds another selection to this one.
    pub fn union_with(&mut self, other: &Self) {
        match other {
            Self::Specific(other) => {
                if let Self::Specific(contracts) = self {
                    contracts.union(other);
                }
            }
            Self::All => *self = Self::All,
        }
    }

    /// Selects `contract_id`.
    pub fn insert(&mut self, contract_id: ContractId) {
        if let Self::Specific(contracts) = self {
            contracts.insert(contract_id);
        }
    }

    /// Returns whether no contracts are selected.
    pub fn is_empty(&self) -> bool {
        matches!(self, Self::Specific(contracts) if contracts.is_empty())
    }

    /// Returns whether `contract_id` is selected.
    fn contains(&self, contract_id: ContractId) -> bool {
        match self {
            Self::Specific(contracts) => contracts.contains(contract_id),
            Self::All => true,
        }
    }
}

/// Generates requested contract artifacts and their creation-bytecode dependencies.
///
/// Contracts in `contracts` retain bytecode in the returned artifact.
/// Contracts in `capture_mir` retain built MIR under `-O none` when no explicit pipeline is
/// configured and final MIR otherwise.
/// Contracts in `capture_evm_ir` retain their final EVM IR in the returned artifact.
/// Values returned by `runtime_data` are emitted as trailing runtime program data.
/// Contracts in `capture_debug_info` retain final instruction locations.
#[tracing::instrument(name = "codegen", level = "debug", skip_all)]
pub fn generate_contract_bytecodes(
    gcx: Gcx<'_>,
    contracts: &ContractSelection,
    capture_mir: &ContractSelection,
    capture_evm_ir: &ContractSelection,
    runtime_data: Option<&RuntimeDataFn<'_>>,
    capture_debug_info: &ContractSelection,
) -> Result<FxHashMap<ContractId, ContractArtifact>> {
    // The bytecode of a failed compilation is withheld, and lowering reports the
    // construct that analysis already rejected as a second, misleading error.
    gcx.dcx().has_errors()?;
    let captures = ContractCaptures {
        bytecode: contracts,
        mir: capture_mir,
        evm_ir: capture_evm_ir,
        runtime_data,
        debug_info: capture_debug_info,
    };
    let mut requested = contracts.clone();
    requested.union_with(capture_mir);
    requested.union_with(capture_evm_ir);
    requested.union_with(capture_debug_info);
    let graph = ContractGraph::discover(gcx, &requested)?;
    let contract_count = gcx.hir.contract_ids().len();

    // Pass debugging writes directly to stdout and stderr, so keep its output ordered.
    let parallel = gcx.sess.is_parallel()
        && !gcx.sess.opts.unstable.print_after_each
        && !gcx.sess.opts.unstable.pass_diff
        && !gcx.sess.opts.unstable.time_passes
        && !gcx.sess.opts.unstable.llm_trace;
    let priorities = if parallel {
        graph.scheduling_priorities(gcx)
    } else {
        // Keep source order, with each contract after the contracts it embeds, so no scheduled
        // contract waits on another.
        let mut priorities = IndexVec::from_vec(vec![0; contract_count]);
        for (rank, &contract_id) in graph.order.iter().rev().enumerate() {
            priorities[contract_id] = rank as u64 + 1;
        }
        priorities
    };
    let jobs = ContractJobs {
        gcx,
        span: tracing::Span::current(),
        captures,
        graph: &graph,
        artifacts: IndexVec::from_vec((0..contract_count).map(|_| OnceLock::new()).collect()),
        scheduled: IndexVec::from_vec((0..contract_count).map(|_| Mutex::new(None)).collect()),
        remaining_inputs: IndexVec::from_vec(
            graph
                .dependencies
                .iter()
                .map(|dependencies| AtomicUsize::new(dependencies.len() + 1))
                .collect(),
        ),
        queue: ContractQueue { jobs: Mutex::new(BinaryHeap::new()), priorities },
    };
    // Every contract is scheduled up front; only its completion waits for the
    // bytecode of the contracts it creates.
    for contract_id in graph.reachable.iter() {
        jobs.queue.push(ContractJob::Schedule(contract_id));
    }
    sync::scope(parallel, |scope| {
        for _ in graph.reachable.iter() {
            jobs.spawn_worker(&scope);
        }
    });
    let artifacts = jobs.artifacts;
    gcx.dcx().has_errors()?;

    let mut generated = FxHashMap::default();
    for (contract_id, artifact) in artifacts.into_iter_enumerated() {
        if graph.reachable.contains(contract_id) {
            generated.insert(
                contract_id,
                artifact.into_inner().expect("contract artifact should have been generated"),
            );
        }
    }
    Ok(generated)
}

#[derive(Clone, Copy)]
struct ContractCaptures<'a> {
    bytecode: &'a ContractSelection,
    mir: &'a ContractSelection,
    evm_ir: &'a ContractSelection,
    runtime_data: Option<&'a RuntimeDataFn<'a>>,
    debug_info: &'a ContractSelection,
}

struct ContractGraph {
    dependencies: IndexVec<ContractId, GrowableBitSet<ContractId>>,
    dependents: IndexVec<ContractId, Vec<ContractId>>,
    reachable: DenseBitSet<ContractId>,
    /// Reachable contracts in source order, each after the contracts it embeds.
    order: Vec<ContractId>,
}

impl ContractGraph {
    #[tracing::instrument(name = "contract_graph", level = "debug", skip_all)]
    fn discover(gcx: Gcx<'_>, contracts: &ContractSelection) -> Result<Self> {
        let contract_count = gcx.hir.contract_ids().len();
        let mut graph = Self {
            dependencies: IndexVec::from_vec(
                (0..contract_count).map(|_| GrowableBitSet::new_empty()).collect(),
            ),
            dependents: IndexVec::from_vec((0..contract_count).map(|_| Vec::new()).collect()),
            reachable: DenseBitSet::new_empty(contract_count),
            order: Vec::new(),
        };
        let mut visiting = DenseBitSet::new_empty(contract_count);
        for contract_id in contracts.into_iter(gcx) {
            graph.discover_contract(gcx, contract_id, &mut visiting)?;
        }
        Ok(graph)
    }

    fn discover_contract(
        &mut self,
        gcx: Gcx<'_>,
        contract_id: ContractId,
        visiting: &mut DenseBitSet<ContractId>,
    ) -> Result {
        if self.reachable.contains(contract_id) {
            return Ok(());
        }

        let contract = gcx.hir.contract(contract_id);
        if contract.kind.is_interface() || contract.kind.is_abstract_contract() {
            return Err(gcx
                .dcx()
                .err("cannot generate creation bytecode for non-deployable contract")
                .span(contract.span)
                .emit());
        }

        if !visiting.insert(contract_id) {
            return Err(gcx
                .dcx()
                .err("recursive contract creation bytecode dependency")
                .span(contract.span)
                .emit());
        }

        let dependencies = gcx.contract_bytecode_dependencies(contract_id);
        // Final assembly links embedded bytecode by source-qualified name.
        let mut names = FxHashMap::default();
        for dependency in dependencies.iter() {
            let name = QualifiedName::of_contract(gcx, dependency);
            if let Some(other) = names.insert(name, dependency) {
                return Err(gcx
                    .dcx()
                    .err(format!("cannot embed two contracts named `{}`", name.as_str()))
                    .span(gcx.hir.contract(dependency).span)
                    .span_note(gcx.hir.contract(other).span, "the other contract is here")
                    .emit());
            }
        }
        for dependency in dependencies.iter() {
            self.dependents[dependency].push(contract_id);
            self.discover_contract(gcx, dependency, visiting)?;
        }
        for dependency in dependencies.iter() {
            self.dependencies[contract_id].insert(dependency);
        }
        self.reachable.insert(contract_id);
        self.order.push(contract_id);
        visiting.remove(contract_id);
        Ok(())
    }

    /// Starts the estimated longest dependency chains first. Completing a
    /// contract waits for the contracts it embeds, so their work is on the path
    /// to every embedding contract. Source-body sizes are a cheap scheduling
    /// estimate; they do not affect what gets compiled.
    fn scheduling_priorities(&self, gcx: Gcx<'_>) -> IndexVec<ContractId, u64> {
        let mut costs = IndexVec::from_vec(vec![0u64; self.dependencies.len()]);
        for id in self.reachable.iter() {
            costs[id] = gcx
                .contract_reachable_functions(id)
                .iter()
                .map(|function| {
                    let span = gcx.hir.function(function).body_span;
                    u64::from(span.hi().to_u32() - span.lo().to_u32())
                })
                .sum::<u64>()
                .max(1);
        }
        let mut priorities = costs.clone();
        let mut remaining = IndexVec::from_vec(self.dependents.iter().map(Vec::len).collect());
        let mut ready = self.reachable.iter().filter(|&id| remaining[id] == 0).collect::<Vec<_>>();
        while let Some(id) = ready.pop() {
            for child in self.dependencies[id].iter() {
                priorities[child] =
                    priorities[child].max(costs[child].saturating_add(priorities[id]));
                remaining[child] -= 1;
                if remaining[child] == 0 {
                    ready.push(child);
                }
            }
        }
        priorities
    }
}

/// One unit of contract code generation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum ContractJob {
    /// Lowers, optimizes, and schedules a contract.
    Schedule(ContractId),
    /// Completes a scheduled contract once the bytecode it embeds is generated.
    Finish(ContractId),
}

/// Workers choose the highest-priority ready job independently of Rayon's task order.
struct ContractQueue {
    jobs: Mutex<BinaryHeap<(u64, Reverse<ContractJob>)>>,
    priorities: IndexVec<ContractId, u64>,
}

impl ContractQueue {
    fn push(&self, job: ContractJob) {
        // Completion is short and unblocks the contracts that embed its bytecode.
        let priority = match job {
            ContractJob::Schedule(id) => self.priorities[id],
            ContractJob::Finish(_) => u64::MAX,
        };
        self.jobs.lock().push((priority, Reverse(job)));
    }

    fn pop(&self) -> ContractJob {
        let (_, Reverse(job)) = self.jobs.lock().pop().expect("each worker has a ready job");
        job
    }
}

/// A contract that is optimized and scheduled, waiting for the bytecode it embeds.
struct ScheduledContract<'gcx> {
    module: Module,
    /// Code generation waiting for linking, runtime assembly, and deployment code, if the
    /// contract has code.
    codegen: Option<Box<EvmCodegen<'gcx>>>,
    /// MIR captured before the optimization pipeline.
    built_mir: Option<Module>,
}

/// Shared state of the contract code generation jobs.
struct ContractJobs<'a, 'gcx> {
    gcx: Gcx<'gcx>,
    /// Parent of the job spans, which run on worker threads.
    span: tracing::Span,
    captures: ContractCaptures<'a>,
    graph: &'a ContractGraph,
    artifacts: IndexVec<ContractId, OnceLock<ContractArtifact>>,
    scheduled: IndexVec<ContractId, Mutex<Option<ScheduledContract<'gcx>>>>,
    /// Unfinished inputs of each contract: its own scheduling and each dependency.
    remaining_inputs: IndexVec<ContractId, AtomicUsize>,
    queue: ContractQueue,
}

impl<'a, 'gcx> ContractJobs<'a, 'gcx> {
    /// Spawns a worker that runs the highest-priority ready job.
    fn spawn_worker<'scope>(&'scope self, scope: &Scope<'_, 'scope>) {
        scope.spawn(move |scope| match self.queue.pop() {
            ContractJob::Schedule(contract_id) => {
                let Ok(scheduled) = self.schedule(contract_id) else { return };
                *self.scheduled[contract_id].lock() = Some(scheduled);
                self.release(&scope, contract_id);
            }
            ContractJob::Finish(contract_id) => {
                let scheduled = self.scheduled[contract_id]
                    .lock()
                    .take()
                    .expect("contract should be scheduled before it finishes");
                let Ok(artifact) = self.finish(contract_id, scheduled) else { return };
                self.artifacts[contract_id]
                    .set(artifact)
                    .expect("contract artifact should only be generated once");
                for &dependent in &self.graph.dependents[contract_id] {
                    self.release(&scope, dependent);
                }
            }
        });
    }

    /// Records one finished input of `contract_id` and completes it after the last one.
    fn release<'scope>(&'scope self, scope: &Scope<'_, 'scope>, contract_id: ContractId) {
        let previous = self.remaining_inputs[contract_id].fetch_sub(1, Ordering::AcqRel);
        assert!(previous > 0, "contract input count underflow");
        if previous == 1 {
            self.queue.push(ContractJob::Finish(contract_id));
            self.spawn_worker(scope);
        }
    }

    /// Lowers, optimizes, and schedules a contract whose embedded bytecode stays deferred.
    fn schedule(&self, contract_id: ContractId) -> Result<ScheduledContract<'gcx>> {
        let Self { gcx, captures, graph, .. } = *self;
        let _span = tracing::debug_span!(
            parent: &self.span,
            "schedule_contract",
            contract = %gcx.contract_fully_qualified_name(contract_id)
        )
        .entered();
        let mut module = lower::lower_contract(gcx, contract_id);
        gcx.dcx().has_errors()?;
        let capture_mir = captures.mir.contains(contract_id);
        let needs_backend = captures.bytecode.contains(contract_id)
            || captures.evm_ir.contains(contract_id)
            || captures.debug_info.contains(contract_id)
            || !graph.dependents[contract_id].is_empty();
        let runtime_data =
            captures.runtime_data.filter(|_| needs_backend).map(|data| data(contract_id));
        append_runtime_data(&mut module, runtime_data.as_ref());
        let capture_built = capture_mir
            && matches!(gcx.sess.opts.optimization, OptimizationMode::None)
            && gcx.sess.opts.unstable.mir_pipeline.is_none();
        let built_mir = (capture_built && needs_backend).then(|| module.clone());
        let codegen = if needs_backend {
            module.set_debug_info_tracked(captures.debug_info.contains(contract_id));
            let mut codegen = Box::new(EvmCodegen::new(gcx));
            codegen.set_capture_mir(capture_mir && !capture_built);
            codegen.set_capture_evm_ir(captures.evm_ir.contains(contract_id));
            codegen.set_capture_debug_info(captures.debug_info.contains(contract_id));
            let scheduled = codegen.schedule_module(&mut module);
            gcx.dcx().has_errors()?;
            scheduled.then_some(codegen)
        } else {
            if capture_mir && !capture_built {
                let _changed = run_pipeline(gcx, &mut module, None);
                gcx.dcx().has_errors()?;
            }
            None
        };
        Ok(ScheduledContract { module, codegen, built_mir })
    }

    /// Supplies the embedded bytecode of a scheduled contract and completes its artifact.
    fn finish(
        &self,
        contract_id: ContractId,
        scheduled: ScheduledContract<'gcx>,
    ) -> Result<ContractArtifact> {
        let Self { gcx, captures, graph, .. } = *self;
        let _span = tracing::debug_span!(
            parent: &self.span,
            "finish_contract",
            contract = %gcx.contract_fully_qualified_name(contract_id)
        )
        .entered();
        let ScheduledContract { module, codegen, built_mir } = scheduled;
        let children = graph.dependencies[contract_id]
            .iter()
            .map(|dependency| {
                let artifact = self.artifacts[dependency]
                    .get()
                    .expect("dependency artifact should have been generated");
                let mut libraries = LibraryTable::default();
                let deployment_relocations =
                    library_relocations(&artifact.deployment_link_references, &mut libraries);
                let runtime_relocations =
                    library_relocations(&artifact.runtime_link_references, &mut libraries);
                let bytecodes = ContractBytecodes {
                    deployment: RelocatableBytecode {
                        bytes: artifact.deployment.clone(),
                        relocations: deployment_relocations,
                        libraries: libraries.clone(),
                    },
                    runtime: RelocatableBytecode {
                        bytes: artifact.runtime.clone(),
                        relocations: runtime_relocations,
                        libraries,
                    },
                };
                (QualifiedName::of_contract(gcx, dependency), bytecodes)
            })
            .collect::<EmbeddedBytecodes>();
        assert_eq!(
            children.len(),
            graph.dependencies[contract_id].count(),
            "embedded contracts must have distinct source-qualified names"
        );
        let artifact = match codegen {
            Some(mut codegen) => {
                let artifact = codegen.finish_module(&module, &children);
                gcx.dcx().has_errors()?;
                artifact
            }
            None => EvmArtifact::default(),
        };
        let capture_mir = captures.mir.contains(contract_id);
        if let Some(limit) = gcx.sess.opts.evm_version.runtime_code_size_limit()
            && artifact.runtime.len() > limit
        {
            let fork = if gcx.sess.opts.evm_version >= EvmVersion::Amsterdam {
                EvmVersion::Amsterdam
            } else {
                EvmVersion::SpuriousDragon
            };
            gcx.dcx()
                .warn(format!(
                    "contract code size is {} bytes and exceeds {} bytes",
                    artifact.runtime.len(),
                    limit
                ))
                .code(error_code!(5574))
                .span(gcx.hir.contract(contract_id).span)
                .note(format!("the limit was introduced in {fork}"))
                .note("this contract may not be deployable on Mainnet")
                .help(
                    "consider enabling the optimizer with a low runs value, turning off revert strings, or using libraries",
                )
                .emit();
        }
        if let Some(limit) = gcx.sess.opts.evm_version.initcode_size_limit()
            && artifact.deployment.len() > limit
        {
            let fork = if gcx.sess.opts.evm_version >= EvmVersion::Amsterdam {
                EvmVersion::Amsterdam
            } else {
                EvmVersion::Shanghai
            };
            gcx.dcx()
                .warn(format!(
                    "contract initcode size is {} bytes and exceeds {} bytes",
                    artifact.deployment.len(),
                    limit
                ))
                .code(error_code!(3860))
                .span(gcx.hir.contract(contract_id).span)
                .note(format!("the limit was introduced in {fork}"))
                .note("this contract may not be deployable on Mainnet")
                .help(
                    "consider enabling the optimizer with a low runs value, turning off revert strings, or using libraries",
                )
                .emit();
        }
        let immutable_references = artifact
            .immutable_references
            .iter()
            .map(|reference| ImmutableReference {
                variable_id: module.immutable(reference.id).variable_id,
                start: reference.code_offset + 1,
                type_size: reference.type_size,
            })
            .collect();
        let deployment_link_references = collect_library_references(
            &artifact.deployment_library_relocations,
            &artifact.libraries,
        );
        let runtime_link_references =
            collect_library_references(&artifact.runtime_library_relocations, &artifact.libraries);
        let mir = capture_mir.then(|| built_mir.unwrap_or(module));

        Ok(ContractArtifact {
            deployment: artifact.deployment.into_boxed_slice().into(),
            runtime: artifact.runtime.into_boxed_slice().into(),
            immutable_references,
            deployment_link_references,
            runtime_link_references,
            mir,
            deployment_evm_ir: artifact.deployment_evm_ir,
            runtime_evm_ir: artifact.runtime_evm_ir,
            deployment_debug_info: artifact.deployment_debug_info,
            runtime_debug_info: artifact.runtime_debug_info,
        })
    }
}

/// Converts named artifact references into identities for embedded bytecode.
fn library_relocations(
    references: &[LibraryReference],
    libraries: &mut LibraryTable,
) -> Vec<LibraryRelocation> {
    references
        .iter()
        .map(|reference| LibraryRelocation {
            offset: reference.start,
            library: libraries.intern(reference.library),
        })
        .collect()
}

/// Resolves the assembler's library relocations to source-qualified names.
fn collect_library_references(
    relocations: &[LibraryRelocation],
    libraries: &LibraryTable,
) -> Vec<LibraryReference> {
    relocations
        .iter()
        .map(|reloc| LibraryReference {
            library: *libraries.get(reloc.library).expect("valid artifact library ID"),
            start: reloc.offset,
        })
        .collect()
}

fn append_runtime_data(module: &mut Module, data: Option<&Bytes>) {
    if let Some(data) = data.filter(|data| !data.is_empty()) {
        module.append_runtime_data(data.clone(), None);
    }
}
