#!/usr/bin/env python3
"""Generates the compiler-owned modules under `crates/sema/src/core/v1/`.

Every function carries a body that any Solidity compiler accepts and that
defines the operation's behaviour; this compiler lowers the entry points by
module identity instead of calling the body. Bodies are written so that every
failure is the `Panic(0x32)` an out-of-range index raises, which is also what
the lowering raises, so the two can be compared call for call.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "crates/sema/src/core/v1"

LICENSE = "// SPDX-License-Identifier: MIT\n// Generated by scripts/core/gen_modules.py; do not edit by hand.\npragma solidity ^0.8.20;\n\n"


def bytes_module() -> str:
    out = [LICENSE, '''/// @notice Checked fixed-width byte loads and stores, bulk copy and fill over
/// `bytes memory`.
/// @dev Compiler-owned module, imported as `solar:core/v1/Bytes.sol`. Every
/// operation checks that the full width fits inside the buffer and reverts
/// with `Panic(0x32)` otherwise, before any byte is written. Reads never pad a
/// short input; writes leave every byte outside the selected range alone.
/// Every body here is ordinary checked Solidity and defines the behaviour; the
/// compiler lowers each entry point to word operations by module identity.
library Bytes {
''']
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`.
    function readBytes{n}(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes{n} result)
    {{
        for (uint256 k; k < {n}; ++k) {{
            result |= bytes{n}(b[offset + k]) >> (8 * k);
        }}
    }}

''')
    out.append('''    /// @dev The 32 bytes of `b` at `offset`, read as a big-endian integer.
    function readUint256BE(bytes memory b, uint256 offset) internal pure returns (uint256 result) {
        for (uint256 k; k < 32; ++k) {
            result = (result << 8) | uint8(b[offset + k]);
        }
    }

''')
    for n in range(1, 33):
        out.append(f'''    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes{n}(bytes memory b, uint256 offset, bytes{n} value) internal pure {{
        for (uint256 k; k < {n}; ++k) {{
            b[offset + k] = value[k];
        }}
    }}

''')
    out.append('''    /// @dev Writes `value` into `b` at `offset` as a big-endian integer.
    function writeUint256BE(bytes memory b, uint256 offset, uint256 value) internal pure {
        for (uint256 k; k < 32; ++k) {
            b[offset + k] = bytes1(uint8(value >> (248 - 8 * k)));
        }
    }

    /// @dev Copies `count` bytes from `src` at `srcOffset` to `dst` at
    /// `dstOffset`. The ranges may overlap: the result is as if the source
    /// were read in full before the first write.
    function copyInto(
        bytes memory dst,
        uint256 dstOffset,
        bytes memory src,
        uint256 srcOffset,
        uint256 count
    ) internal pure {
        // Both ranges are validated before anything is written, so a copy
        // running downwards fails on its range the way one running upwards
        // does, rather than on the arithmetic reaching its far end.
        if (
            count > dst.length || dstOffset > dst.length - count || count > src.length
                || srcOffset > src.length - count
        ) count = _outOfBounds();
        if (dstOffset > srcOffset) {
            for (uint256 k = count; k > 0; --k) {
                dst[dstOffset + k - 1] = src[srcOffset + k - 1];
            }
        } else {
            for (uint256 k; k < count; ++k) {
                dst[dstOffset + k] = src[srcOffset + k];
            }
        }
    }

    /// @dev Sets `count` bytes of `dst` at `offset` to `value`.
    function fill(bytes memory dst, uint256 offset, uint256 count, bytes1 value) internal pure {
        for (uint256 k; k < count; ++k) {
            dst[offset + k] = value;
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def arrays_module() -> str:
    element_types = (
        [f"uint{b}" for b in range(8, 257, 8)]
        + [f"int{b}" for b in range(8, 257, 8)]
        + [f"bytes{n}" for n in range(1, 33)]
        + ["address", "bool"]
    )
    out = [LICENSE, '''/// @notice Shrink-only truncation of dynamic memory arrays.
/// @dev Compiler-owned module, imported as `solar:core/v1/Arrays.sol`.
/// `truncate` sets an array's length to `n`, which must be at most the current
/// length, and every alias of the array observes the new length from then on:
/// later indexing checks use it, and the elements past it are no longer
/// reachable through the array. Nothing is reclaimed and the array cannot grow
/// back. There is no portable Solidity spelling of this operation, so each
/// body is one memory-safe assembly store of the length word; the compiler
/// lowers each entry point to its own length write by module identity, so the
/// assembly is never compiled here.
library Arrays {
''']
    for ty in element_types:
        out.append(f'''    /// @dev Shortens `a` to `n` elements.
    function truncate({ty}[] memory a, uint256 n) internal pure {{
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {{
            mstore(a, n)
        }}
    }}

''')
    out.append('''    /// @dev Shortens `a` to `n` bytes.
    function truncate(bytes memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` bytes.
    function truncate(string memory a, uint256 n) internal pure {
        if (n > bytes(a).length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


(ROOT / "Bytes.sol").write_text(bytes_module())
(ROOT / "Arrays.sol").write_text(arrays_module())
for name in ("Bytes.sol", "Arrays.sol"):
    path = ROOT / name
    print(path, path.stat().st_size, "bytes")
