#!/usr/bin/env python3
"""Generates the compiler-owned modules under `crates/sema/src/core/v1/`.

Every function carries a body that any Solidity compiler accepts and that
defines the operation's behaviour; this compiler lowers the entry points by
module identity instead of calling the body. Bodies are written so that every
failure is the `Panic(0x32)` an out-of-range index raises, which is also what
the lowering raises, so the two can be compared call for call.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "crates/sema/src/core/v1"

LICENSE = "// SPDX-License-Identifier: MIT\n// Generated by scripts/core/gen_modules.py; do not edit by hand.\npragma solidity ^0.8.20;\n\n"


def bytes_module() -> str:
    out = [LICENSE, '''/// @notice Checked fixed-width byte loads and stores, bulk copy and fill over
/// `bytes memory`.
/// @dev Compiler-owned module, imported as `solar:core/v1/Bytes.sol`. Every
/// operation checks that the full width fits inside the buffer and reverts
/// with `Panic(0x32)` otherwise, before any byte is written. Reads never pad a
/// short input; writes leave every byte outside the selected range alone.
/// Every body here is ordinary checked Solidity and defines the behaviour; the
/// compiler lowers each entry point to word operations by module identity.
library Bytes {
''']
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`.
    function readBytes{n}(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes{n} result)
    {{
        for (uint256 k; k < {n}; ++k) {{
            result |= bytes{n}(b[offset + k]) >> (8 * k);
        }}
    }}

''')
    out.append('''    /// @dev The 32 bytes of `b` at `offset`, read as a big-endian integer.
    function readUint256BE(bytes memory b, uint256 offset) internal pure returns (uint256 result) {
        for (uint256 k; k < 32; ++k) {
            result = (result << 8) | uint8(b[offset + k]);
        }
    }

''')
    for n in range(1, 33):
        out.append(f'''    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes{n}(bytes memory b, uint256 offset, bytes{n} value) internal pure {{
        for (uint256 k; k < {n}; ++k) {{
            b[offset + k] = value[k];
        }}
    }}

''')
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes{n}(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes{n} result)
    {{
        if (offset > b.length || b.length - offset < {n}) return (false, bytes{n}(0));
        return (true, readBytes{n}(b, offset));
    }}

''')
    out.append('''    /// @dev The 32 bytes of `b` at `offset` as a big-endian integer, or `false`
    /// and zero when they do not all lie inside `b`.
    function tryReadUint256BE(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, uint256 result)
    {
        if (offset > b.length || b.length - offset < 32) return (false, 0);
        return (true, readUint256BE(b, offset));
    }

''')
    out.append('''    /// @dev Writes `value` into `b` at `offset` as a big-endian integer.
    function writeUint256BE(bytes memory b, uint256 offset, uint256 value) internal pure {
        for (uint256 k; k < 32; ++k) {
            b[offset + k] = bytes1(uint8(value >> (248 - 8 * k)));
        }
    }

    /// @dev Copies `count` bytes from `src` at `srcOffset` to `dst` at
    /// `dstOffset`. The ranges may overlap: the result is as if the source
    /// were read in full before the first write.
    function copyInto(
        bytes memory dst,
        uint256 dstOffset,
        bytes memory src,
        uint256 srcOffset,
        uint256 count
    ) internal pure {
        // Both ranges are validated before anything is written, so a copy
        // running downwards fails on its range the way one running upwards
        // does, rather than on the arithmetic reaching its far end.
        if (
            count > dst.length || dstOffset > dst.length - count || count > src.length
                || srcOffset > src.length - count
        ) count = _outOfBounds();
        if (dstOffset > srcOffset) {
            for (uint256 k = count; k > 0; --k) {
                dst[dstOffset + k - 1] = src[srcOffset + k - 1];
            }
        } else {
            for (uint256 k; k < count; ++k) {
                dst[dstOffset + k] = src[srcOffset + k];
            }
        }
    }

    /// @dev Sets `count` bytes of `dst` at `offset` to `value`.
    function fill(bytes memory dst, uint256 offset, uint256 count, bytes1 value) internal pure {
        for (uint256 k; k < count; ++k) {
            dst[offset + k] = value;
        }
    }

    /// @dev Whether `a` and `b` have the same length and the same bytes. This
    /// is an exact comparison, a word at a time, not a comparison of hashes.
    function equals(bytes memory a, bytes memory b) internal pure returns (bool) {
        uint256 n = a.length;
        if (n != b.length) return false;
        uint256 i;
        while (i + 32 <= n) {
            if (readBytes32(a, i) != readBytes32(b, i)) return false;
            i += 32;
        }
        if (i == n) return true;
        // What is left is shorter than a word. One more word pulled back to
        // end where the input ends covers it; below a word, a byte at a time.
        if (n >= 32) return readBytes32(a, n - 32) == readBytes32(b, n - 32);
        for (; i < n; ++i) {
            if (a[i] != b[i]) return false;
        }
        return true;
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def arrays_module() -> str:
    element_types = (
        [f"uint{b}" for b in range(8, 257, 8)]
        + [f"int{b}" for b in range(8, 257, 8)]
        + [f"bytes{n}" for n in range(1, 33)]
        + ["address", "bool"]
    )
    out = [LICENSE, '''/// @notice Shrink-only truncation of dynamic memory arrays.
/// @dev Compiler-owned module, imported as `solar:core/v1/Arrays.sol`.
/// `truncate` sets an array's length to `n`, which must be at most the current
/// length, and every alias of the array observes the new length from then on:
/// later indexing checks use it, and the elements past it are no longer
/// reachable through the array. Nothing is reclaimed and the array cannot grow
/// back. There is no portable Solidity spelling of this operation, so each
/// body is one memory-safe assembly store of the length word; the compiler
/// lowers each entry point to its own length write by module identity, so the
/// assembly is never compiled here.
library Arrays {
''']
    for ty in element_types:
        out.append(f'''    /// @dev Shortens `a` to `n` elements.
    function truncate({ty}[] memory a, uint256 n) internal pure {{
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {{
            mstore(a, n)
        }}
    }}

''')
    out.append('''    /// @dev Shortens `a` to `n` bytes.
    function truncate(bytes memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` bytes.
    function truncate(string memory a, uint256 n) internal pure {
        if (n > bytes(a).length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def calldata_bytes_module() -> str:
    out = [LICENSE, '''/// @notice Checked fixed-width byte loads from `bytes calldata`, and bulk copy
/// out of it.
/// @dev Compiler-owned module, imported as `solar:core/v1/CalldataBytes.sol`.
/// Solidity does not let two functions differ only in the data location of a
/// parameter, so the calldata operations live here under the names `Bytes`
/// uses for memory. Every read checks that the full width lies inside the
/// slice and reverts with `Panic(0x32)` otherwise; nothing is padded.
/// `copyInto` validates both ranges before it writes. Every body here is
/// ordinary checked Solidity and defines the behaviour; the compiler lowers
/// each entry point to `calldataload` and `calldatacopy` by module identity.
library CalldataBytes {
''']
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`.
    function readBytes{n}(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes{n} result)
    {{
        for (uint256 k; k < {n}; ++k) {{
            result |= bytes{n}(b[offset + k]) >> (8 * k);
        }}
    }}

''')
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes{n}(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes{n} result)
    {{
        if (offset > b.length || b.length - offset < {n}) return (false, bytes{n}(0));
        return (true, readBytes{n}(b, offset));
    }}

''')
    out.append('''    /// @dev The 32 bytes of `b` at `offset`, read as a big-endian integer.
    function readUint256BE(bytes calldata b, uint256 offset) internal pure returns (uint256 result) {
        for (uint256 k; k < 32; ++k) {
            result = (result << 8) | uint8(b[offset + k]);
        }
    }

    /// @dev The 32 bytes of `b` at `offset` as a big-endian integer, or `false`
    /// and zero when they do not all lie inside `b`.
    function tryReadUint256BE(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bool ok, uint256 result)
    {
        if (offset > b.length || b.length - offset < 32) return (false, 0);
        return (true, readUint256BE(b, offset));
    }

    /// @dev Copies `count` bytes of `src` at `srcOffset` into `dst` at
    /// `dstOffset`.
    function copyInto(
        bytes memory dst,
        uint256 dstOffset,
        bytes calldata src,
        uint256 srcOffset,
        uint256 count
    ) internal pure {
        // Both ranges are validated before anything is written.
        if (
            count > dst.length || dstOffset > dst.length - count || count > src.length
                || srcOffset > src.length - count
        ) count = _outOfBounds();
        for (uint256 k; k < count; ++k) {
            dst[dstOffset + k] = src[srcOffset + k];
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def cast_module() -> str:
    out = [LICENSE, '''/// @notice Narrowing casts that fail instead of truncating.
/// @dev Compiler-owned module, imported as `solar:core/v1/Cast.sol`. A
/// Solidity cast such as `uint40(x)` keeps the low bits and drops the rest
/// without a word; these revert with `Panic(0x11)`, the arithmetic overflow
/// panic, when `x` does not fit the target type, and otherwise return it
/// unchanged. Casts that cannot lose anything are not here: write them as
/// ordinary conversions.
library Cast {
''']
    for bits in range(8, 256, 8):
        out.append(f'''    /// @dev `x` as a `uint{bits}`.
    function toUint{bits}(uint256 x) internal pure returns (uint{bits}) {{
        if (x > type(uint{bits}).max) _overflow();
        return uint{bits}(x);
    }}

''')
    for bits in range(8, 256, 8):
        out.append(f'''    /// @dev `x` as an `int{bits}`.
    function toInt{bits}(int256 x) internal pure returns (int{bits}) {{
        if (x < type(int{bits}).min || x > type(int{bits}).max) _overflow();
        return int{bits}(x);
    }}

''')
    out.append('''    /// @dev `x` as an `int256`.
    function toInt256(uint256 x) internal pure returns (int256) {
        if (x > uint256(type(int256).max)) _overflow();
        return int256(x);
    }

    /// @dev `x` as a `uint256`.
    function toUint256(int256 x) internal pure returns (uint256) {
        if (x < 0) _overflow();
        return uint256(x);
    }

    /// @dev Raises the `Panic(0x11)` a checked addition raises, which is the
    /// portable spelling of a value that does not fit.
    function _overflow() private pure {
        uint256 most = type(uint256).max;
        most += 1;
    }
}
''')
    return "".join(out)


(ROOT / "Bytes.sol").write_text(bytes_module())
(ROOT / "Arrays.sol").write_text(arrays_module())
(ROOT / "Cast.sol").write_text(cast_module())
(ROOT / "CalldataBytes.sol").write_text(calldata_bytes_module())
for name in ("Bytes.sol", "Arrays.sol", "Cast.sol", "CalldataBytes.sol"):
    path = ROOT / name
    print(path, path.stat().st_size, "bytes")
