#!/usr/bin/env python3
"""Generates the compiler-owned modules under `crates/sema/src/core/v1/`.

Every function carries a body that any Solidity compiler accepts and that
defines the operation's behaviour; this compiler lowers the entry points by
module identity instead of calling the body. Bodies are written so that every
failure is the `Panic(0x32)` an out-of-range index raises, which is also what
the lowering raises, so the two can be compared call for call.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "crates/sema/src/core/v1"

LICENSE = "// SPDX-License-Identifier: MIT\n// Generated by scripts/core/gen_modules.py; do not edit by hand.\npragma solidity ^0.8.20;\n\n"


def bytes_module() -> str:
    out = [LICENSE, '''/// @notice Checked fixed-width byte loads and stores, bulk copy and fill over
/// `bytes memory`.
/// @dev Compiler-owned module, imported as `solar:core/v1/Bytes.sol`. Every
/// operation checks that the full width fits inside the buffer and reverts
/// with `Panic(0x32)` otherwise, before any byte is written. Reads never pad a
/// short input; writes leave every byte outside the selected range alone.
/// Every body here is ordinary checked Solidity and defines the behaviour; the
/// compiler lowers each entry point to word operations by module identity.
library Bytes {
''']
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`.
    function readBytes{n}(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes{n} result)
    {{
        for (uint256 k; k < {n}; ++k) {{
            result |= bytes{n}(b[offset + k]) >> (8 * k);
        }}
    }}

''')
    out.append('''    /// @dev The 32 bytes of `b` at `offset`, read as a big-endian integer.
    function readUint256BE(bytes memory b, uint256 offset) internal pure returns (uint256 result) {
        for (uint256 k; k < 32; ++k) {
            result = (result << 8) | uint8(b[offset + k]);
        }
    }

''')
    for n in range(1, 33):
        out.append(f'''    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes{n}(bytes memory b, uint256 offset, bytes{n} value) internal pure {{
        for (uint256 k; k < {n}; ++k) {{
            b[offset + k] = value[k];
        }}
    }}

''')
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes{n}(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes{n} result)
    {{
        if (offset > b.length || b.length - offset < {n}) return (false, bytes{n}(0));
        return (true, readBytes{n}(b, offset));
    }}

''')
    out.append('''    /// @dev The 32 bytes of `b` at `offset` as a big-endian integer, or `false`
    /// and zero when they do not all lie inside `b`.
    function tryReadUint256BE(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, uint256 result)
    {
        if (offset > b.length || b.length - offset < 32) return (false, 0);
        return (true, readUint256BE(b, offset));
    }

''')
    out.append('''    /// @dev Writes `value` into `b` at `offset` as a big-endian integer.
    function writeUint256BE(bytes memory b, uint256 offset, uint256 value) internal pure {
        for (uint256 k; k < 32; ++k) {
            b[offset + k] = bytes1(uint8(value >> (248 - 8 * k)));
        }
    }

    /// @dev Copies `count` bytes from `src` at `srcOffset` to `dst` at
    /// `dstOffset`. The ranges may overlap: the result is as if the source
    /// were read in full before the first write.
    function copyInto(
        bytes memory dst,
        uint256 dstOffset,
        bytes memory src,
        uint256 srcOffset,
        uint256 count
    ) internal pure {
        // Both ranges are validated before anything is written, so a copy
        // running downwards fails on its range the way one running upwards
        // does, rather than on the arithmetic reaching its far end.
        if (
            count > dst.length || dstOffset > dst.length - count || count > src.length
                || srcOffset > src.length - count
        ) count = _outOfBounds();
        if (dstOffset > srcOffset) {
            for (uint256 k = count; k > 0; --k) {
                dst[dstOffset + k - 1] = src[srcOffset + k - 1];
            }
        } else {
            for (uint256 k; k < count; ++k) {
                dst[dstOffset + k] = src[srcOffset + k];
            }
        }
    }

    /// @dev Sets `count` bytes of `dst` at `offset` to `value`.
    function fill(bytes memory dst, uint256 offset, uint256 count, bytes1 value) internal pure {
        for (uint256 k; k < count; ++k) {
            dst[offset + k] = value;
        }
    }

    /// @dev Whether `a` and `b` have the same length and the same bytes. This
    /// is an exact comparison, a word at a time, not a comparison of hashes.
    function equals(bytes memory a, bytes memory b) internal pure returns (bool) {
        uint256 n = a.length;
        if (n != b.length) return false;
        uint256 i;
        while (i + 32 <= n) {
            if (readBytes32(a, i) != readBytes32(b, i)) return false;
            i += 32;
        }
        if (i == n) return true;
        // What is left is shorter than a word. One more word pulled back to
        // end where the input ends covers it; below a word, a byte at a time.
        if (n >= 32) return readBytes32(a, n - 32) == readBytes32(b, n - 32);
        for (; i < n; ++i) {
            if (a[i] != b[i]) return false;
        }
        return true;
    }

    /// @dev Whether the `b.length` bytes of `a` at `offset` are the bytes of
    /// `b`. Reverts with `Panic(0x32)` unless they all lie inside `a`, before
    /// comparing any byte.
    function equalsAt(bytes memory a, uint256 offset, bytes memory b) internal pure returns (bool) {
        uint256 count = b.length;
        if (offset > a.length || count > a.length - offset) offset = _outOfBounds();
        for (uint256 k; k < count; ++k) {
            if (a[offset + k] != b[k]) return false;
        }
        return true;
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def arrays_module() -> str:
    element_types = (
        [f"uint{b}" for b in range(8, 257, 8)]
        + [f"int{b}" for b in range(8, 257, 8)]
        + [f"bytes{n}" for n in range(1, 33)]
        + ["address", "bool"]
    )
    out = [LICENSE, '''/// @notice Shrink-only truncation of dynamic memory arrays.
/// @dev Compiler-owned module, imported as `solar:core/v1/Arrays.sol`.
/// `truncate` sets an array's length to `n`, which must be at most the current
/// length, and every alias of the array observes the new length from then on:
/// later indexing checks use it, and the elements past it are no longer
/// reachable through the array. Nothing is reclaimed and the array cannot grow
/// back. There is no portable Solidity spelling of this operation, so each
/// body is one memory-safe assembly store of the length word; the compiler
/// lowers each entry point to its own length write by module identity, so the
/// assembly is never compiled here.
library Arrays {
''']
    for ty in element_types:
        out.append(f'''    /// @dev Shortens `a` to `n` elements.
    function truncate({ty}[] memory a, uint256 n) internal pure {{
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {{
            mstore(a, n)
        }}
    }}

''')
    out.append('''    /// @dev Shortens `a` to `n` bytes.
    function truncate(bytes memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` bytes.
    function truncate(string memory a, uint256 n) internal pure {
        if (n > bytes(a).length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def word_arrays_module() -> str:
    out = [LICENSE, '''import {Arrays} from "solar:core/v1/Arrays.sol";

/// @notice Checked algorithms over one-word dynamic memory arrays.
/// @dev Compiler-owned module, imported as `solar:core/v1/WordArrays.sol`.
/// The bodies are portable checked Solidity and define the behavior; Solar
/// lowers every overload to one shared implementation by module identity.
library WordArrays {
''']
    duplicate_types = {
        "uint256": "uint256(a[i])",
        "int256": "uint256(a[i])",
        "address": "uint256(uint160(a[i]))",
        "bytes32": "uint256(a[i])",
    }
    for ty, value in duplicate_types.items():
        out.append(f'''    /// @dev Sorts `a` in ascending order.
    function sort({ty}[] memory a) internal pure {{
        for (uint256 i = 1; i < a.length; ++i) {{
            {ty} value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {{
                a[j] = a[j - 1];
                --j;
            }}
            a[j] = value;
        }}
    }}

''')
        out.append(f'''    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate({ty}[] memory a) internal pure returns (bool) {{
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {{
            --i;
            uint256 slot =
                mulmod({value}, 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {{
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }}
            seen[slot] = i + 1;
        }}
        return false;
    }}

''')
        out.append(f'''    /// @dev A new array holding the elements of `a`.
    function copy({ty}[] memory a) internal pure returns ({ty}[] memory c) {{
        c = new {ty}[](a.length);
        for (uint256 i; i < a.length; ++i) {{
            c[i] = a[i];
        }}
    }}

''')
        out.append(f'''    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted({ty}[] memory a) internal pure {{
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {{
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }}
        Arrays.truncate(a, write);
    }}

''')
        out.append(f'''    /// @dev The sorted union of sorted, duplicate-free `a` and `b`.
    function union({ty}[] memory a, {ty}[] memory b)
        internal
        pure
        returns ({ty}[] memory c)
    {{
        c = new {ty}[](a.length + b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {{
            {ty} u = a[i];
            {ty} v = b[j];
            if (u == v) {{
                c[k] = u;
                ++k;
                ++i;
                ++j;
            }} else if (u > v) {{
                c[k] = v;
                ++k;
                ++j;
            }} else {{
                c[k] = u;
                ++k;
                ++i;
            }}
        }}
        while (i < a.length) {{
            c[k] = a[i];
            ++k;
            ++i;
        }}
        while (j < b.length) {{
            c[k] = b[j];
            ++k;
            ++j;
        }}
        Arrays.truncate(c, k);
    }}

    /// @dev The sorted intersection of sorted, duplicate-free `a` and `b`.
    function intersection({ty}[] memory a, {ty}[] memory b)
        internal
        pure
        returns ({ty}[] memory c)
    {{
        c = new {ty}[](a.length < b.length ? a.length : b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {{
            {ty} u = a[i];
            {ty} v = b[j];
            if (u == v) {{
                c[k] = u;
                ++k;
                ++i;
                ++j;
            }} else if (u > v) {{
                ++j;
            }} else {{
                ++i;
            }}
        }}
        Arrays.truncate(c, k);
    }}

    /// @dev The sorted difference of sorted, duplicate-free `a` and `b`.
    function difference({ty}[] memory a, {ty}[] memory b)
        internal
        pure
        returns ({ty}[] memory c)
    {{
        c = new {ty}[](a.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {{
            {ty} u = a[i];
            {ty} v = b[j];
            if (u == v) {{
                ++i;
                ++j;
            }} else if (u > v) {{
                ++j;
            }} else {{
                c[k] = u;
                ++k;
                ++i;
            }}
        }}
        while (i < a.length) {{
            c[k] = a[i];
            ++k;
            ++i;
        }}
        Arrays.truncate(c, k);
    }}

''')
        word = "uint256({})" if ty == "int256" else "{}"
        before = word.format("keys[j - 1]") + " > " + word.format("key")
        out.append(f'''    /// @dev Sorts `keys` by their word values with `values` moved alongside,
    /// keeps one of each key, and gives it the sum of the values its copies had.
    /// Both arrays shrink to the kept keys. The arrays must have one length, and
    /// every sum must fit a word.
    function groupSum({ty}[] memory keys, uint256[] memory values) internal pure {{
        uint256 n = keys.length;
        if (values.length != n) n = _outOfBounds();
        if (n < 2) return;
        for (uint256 i = 1; i < n; ++i) {{
            {ty} key = keys[i];
            uint256 value = values[i];
            uint256 j = i;
            while (j != 0 && {before}) {{
                keys[j] = keys[j - 1];
                values[j] = values[j - 1];
                --j;
            }}
            keys[j] = key;
            values[j] = value;
        }}
        uint256 kept = 0;
        uint256 sum = values[0];
        for (uint256 i = 1; i < n; ++i) {{
            if (keys[i] == keys[kept]) {{
                sum += values[i];
            }} else {{
                values[kept] = sum;
                keys[++kept] = keys[i];
                sum = values[i];
            }}
        }}
        values[kept] = sum;
        Arrays.truncate(keys, kept + 1);
        Arrays.truncate(values, kept + 1);
    }}

''')
    out.append('''    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def calldata_bytes_module() -> str:
    out = [LICENSE, '''/// @notice Checked fixed-width byte loads from `bytes calldata`, and bulk copy
/// out of it.
/// @dev Compiler-owned module, imported as `solar:core/v1/CalldataBytes.sol`.
/// Solidity does not let two functions differ only in the data location of a
/// parameter, so the calldata operations live here under the names `Bytes`
/// uses for memory. Every read checks that the full width lies inside the
/// slice and reverts with `Panic(0x32)` otherwise; nothing is padded.
/// `copyInto` validates both ranges before it writes. Every body here is
/// ordinary checked Solidity and defines the behaviour; the compiler lowers
/// each entry point to `calldataload` and `calldatacopy` by module identity.
library CalldataBytes {
''']
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`.
    function readBytes{n}(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes{n} result)
    {{
        for (uint256 k; k < {n}; ++k) {{
            result |= bytes{n}(b[offset + k]) >> (8 * k);
        }}
    }}

''')
    for n in range(1, 33):
        out.append(f'''    /// @dev The {n} byte{"s" if n > 1 else ""} of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes{n}(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes{n} result)
    {{
        if (offset > b.length || b.length - offset < {n}) return (false, bytes{n}(0));
        return (true, readBytes{n}(b, offset));
    }}

''')
    out.append('''    /// @dev The 32 bytes of `b` at `offset`, read as a big-endian integer.
    function readUint256BE(bytes calldata b, uint256 offset) internal pure returns (uint256 result) {
        for (uint256 k; k < 32; ++k) {
            result = (result << 8) | uint8(b[offset + k]);
        }
    }

    /// @dev The 32 bytes of `b` at `offset` as a big-endian integer, or `false`
    /// and zero when they do not all lie inside `b`.
    function tryReadUint256BE(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bool ok, uint256 result)
    {
        if (offset > b.length || b.length - offset < 32) return (false, 0);
        return (true, readUint256BE(b, offset));
    }

    /// @dev Copies `count` bytes of `src` at `srcOffset` into `dst` at
    /// `dstOffset`.
    function copyInto(
        bytes memory dst,
        uint256 dstOffset,
        bytes calldata src,
        uint256 srcOffset,
        uint256 count
    ) internal pure {
        // Both ranges are validated before anything is written.
        if (
            count > dst.length || dstOffset > dst.length - count || count > src.length
                || srcOffset > src.length - count
        ) count = _outOfBounds();
        for (uint256 k; k < count; ++k) {
            dst[dstOffset + k] = src[srcOffset + k];
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
''')
    return "".join(out)


def cast_module() -> str:
    out = [LICENSE, '''/// @notice Narrowing casts that fail instead of truncating.
/// @dev Compiler-owned module, imported as `solar:core/v1/Cast.sol`. A
/// Solidity cast such as `uint40(x)` keeps the low bits and drops the rest
/// without a word; these revert with `Panic(0x11)`, the arithmetic overflow
/// panic, when `x` does not fit the target type, and otherwise return it
/// unchanged. Casts that cannot lose anything are not here: write them as
/// ordinary conversions.
library Cast {
''']
    for bits in range(8, 256, 8):
        out.append(f'''    /// @dev `x` as a `uint{bits}`.
    function toUint{bits}(uint256 x) internal pure returns (uint{bits}) {{
        if (x > type(uint{bits}).max) _overflow();
        return uint{bits}(x);
    }}

''')
    for bits in range(8, 256, 8):
        out.append(f'''    /// @dev `x` as an `int{bits}`.
    function toInt{bits}(int256 x) internal pure returns (int{bits}) {{
        if (x < type(int{bits}).min || x > type(int{bits}).max) _overflow();
        return int{bits}(x);
    }}

''')
    out.append('''    /// @dev `x` as an `int256`.
    function toInt256(uint256 x) internal pure returns (int256) {
        if (x > uint256(type(int256).max)) _overflow();
        return int256(x);
    }

    /// @dev `x` as a `uint256`.
    function toUint256(int256 x) internal pure returns (uint256) {
        if (x < 0) _overflow();
        return uint256(x);
    }

    /// @dev Raises the `Panic(0x11)` a checked addition raises, which is the
    /// portable spelling of a value that does not fit.
    function _overflow() private pure {
        uint256 most = type(uint256).max;
        most += 1;
    }
}
''')
    return "".join(out)


(ROOT / "Bytes.sol").write_text(bytes_module())
(ROOT / "Arrays.sol").write_text(arrays_module())
(ROOT / "WordArrays.sol").write_text(word_arrays_module())
(ROOT / "Cast.sol").write_text(cast_module())
(ROOT / "CalldataBytes.sol").write_text(calldata_bytes_module())
for name in ("Bytes.sol", "Arrays.sol", "WordArrays.sol", "Cast.sol", "CalldataBytes.sol"):
    path = ROOT / name
    print(path, path.stat().st_size, "bytes")
