name: Bug Report
description: Create a bug report
type: Bug
labels: ["C-bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for filing a bug report! 🐛 Please provide a short summary of the bug,
              along with any information you feel relevant to replicating the bug.
    - type: textarea
      attributes:
          label: Reproducible steps
          placeholder: |
              I tried this code:

              ```solidity
              <code>
              ```

              I expected to see this happen: *explanation*

              Instead, this happened: *explanation*
      validations:
          required: true
    - type: input
      attributes:
          label: Solar version
          description: |
              What version of Solar are you using? (`solar --version`)
          placeholder: |
              <version>
      validations:
          required: true
