//! `-Zdataflow` only reads MIR, so requesting it leaves generated bytecode unchanged.

use solar::interface::source_map::{FileLoader, RealFileLoader};
use std::process::Command;

const SOLAR: &str = env!("CARGO_BIN_EXE_solar");
const FIXTURES: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/ui/codegen/dataflow/reentrancy");
const SOURCES: &[&str] = &["cross_contract.sol", "openzeppelin_guard.sol", "create_callback.sol"];

fn compile_to(dir: &std::path::Path, source: &str, mode: &str, extra: &[&str]) -> String {
    let output = Command::new(SOLAR)
        .current_dir(FIXTURES)
        .args(["--allow", "2264", "--threads", "1", "-O", mode, "--emit=bin,bin-runtime"])
        .arg("--out-dir")
        .arg(dir)
        .args(extra)
        .arg(source)
        .output()
        .expect("run compiler");
    assert!(output.status.success(), "{}", String::from_utf8_lossy(&output.stderr));
    RealFileLoader.load_file(&dir.join("combined.json")).expect("read combined JSON")
}

#[test]
fn dataflow_analyses_are_bytecode_neutral() {
    for source in SOURCES {
        for mode in ["none", "gas", "size"] {
            let baseline = tempfile::tempdir().unwrap();
            let analyzed = tempfile::tempdir().unwrap();
            let expected = compile_to(baseline.path(), source, mode, &[]);
            let actual = compile_to(
                analyzed.path(),
                source,
                mode,
                &[
                    "-Zdataflow=storage,taint,reentrancy,liveness,intervals,rounding,units",
                    "-Zdataflow-k=1",
                ],
            );
            assert_eq!(actual, expected, "{source} with -O {mode}");
        }
    }
}
