// ported-from: test/libsolidity/syntaxTests/abiEncoder/v1_accessing_public_state_variable_via_v1_type.sol
pragma abicoder v1;
struct Item {
    uint x;
    uint y;
}

contract D {
    Item[][][] public items;

    function test() public view returns (uint) {
        // The autogenerated getters to not use ABI encoder.
        (uint a, uint b) = this.items(1, 2, 3);
        return a + b;
    }
}
