// SPDX-License-Identifier: MIT
// Generated by scripts/core/gen_modules.py; do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Shrink-only truncation of dynamic memory arrays.
/// @dev Compiler-owned module, imported as `solar:core/v1/Arrays.sol`.
/// `truncate` sets an array's length to `n`, which must be at most the current
/// length, and every alias of the array observes the new length from then on:
/// later indexing checks use it, and the elements past it are no longer
/// reachable through the array. Nothing is reclaimed and the array cannot grow
/// back. There is no portable Solidity spelling of this operation, so each
/// body is one memory-safe assembly store of the length word; the compiler
/// lowers each entry point to its own length write by module identity, so the
/// assembly is never compiled here.
library Arrays {
    /// @dev Shortens `a` to `n` elements.
    function truncate(uint8[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint16[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint24[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint32[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint40[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint48[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint56[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint64[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint72[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint80[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint88[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint96[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint104[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint112[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint120[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint128[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint136[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint144[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint152[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint160[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint168[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint176[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint184[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint192[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint200[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint208[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint216[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint224[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint232[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint240[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint248[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(uint256[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int8[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int16[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int24[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int32[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int40[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int48[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int56[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int64[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int72[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int80[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int88[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int96[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int104[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int112[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int120[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int128[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int136[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int144[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int152[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int160[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int168[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int176[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int184[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int192[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int200[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int208[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int216[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int224[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int232[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int240[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int248[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(int256[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes1[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes2[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes3[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes4[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes5[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes6[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes7[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes8[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes9[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes10[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes11[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes12[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes13[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes14[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes15[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes16[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes17[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes18[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes19[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes20[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes21[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes22[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes23[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes24[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes25[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes26[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes27[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes28[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes29[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes30[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes31[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bytes32[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(address[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` elements.
    function truncate(bool[] memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` bytes.
    function truncate(bytes memory a, uint256 n) internal pure {
        if (n > a.length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Shortens `a` to `n` bytes.
    function truncate(string memory a, uint256 n) internal pure {
        if (n > bytes(a).length) n = _outOfBounds();
        assembly ("memory-safe") {
            mstore(a, n)
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
