// SPDX-License-Identifier: MIT
// Generated by scripts/core/gen_modules.py; do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Checked fixed-width byte loads and stores, bulk copy, fill and
/// slices over `bytes memory`.
/// @dev Compiler-owned module, imported as `solar:core/v1/Bytes.sol`. Every
/// operation checks that the full width fits inside the buffer and reverts
/// with `Panic(0x32)` otherwise, before any byte is written. Reads never pad a
/// short input; writes leave every byte outside the selected range alone.
/// Every body here is ordinary checked Solidity and defines the behaviour; the
/// compiler lowers each entry point to word operations by module identity.
library Bytes {
    /// @dev The 1 byte of `b` at `offset`.
    function readBytes1(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes1 result)
    {
        for (uint256 k; k < 1; ++k) {
            result |= bytes1(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 2 bytes of `b` at `offset`.
    function readBytes2(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes2 result)
    {
        for (uint256 k; k < 2; ++k) {
            result |= bytes2(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 3 bytes of `b` at `offset`.
    function readBytes3(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes3 result)
    {
        for (uint256 k; k < 3; ++k) {
            result |= bytes3(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 4 bytes of `b` at `offset`.
    function readBytes4(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes4 result)
    {
        for (uint256 k; k < 4; ++k) {
            result |= bytes4(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 5 bytes of `b` at `offset`.
    function readBytes5(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes5 result)
    {
        for (uint256 k; k < 5; ++k) {
            result |= bytes5(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 6 bytes of `b` at `offset`.
    function readBytes6(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes6 result)
    {
        for (uint256 k; k < 6; ++k) {
            result |= bytes6(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 7 bytes of `b` at `offset`.
    function readBytes7(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes7 result)
    {
        for (uint256 k; k < 7; ++k) {
            result |= bytes7(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 8 bytes of `b` at `offset`.
    function readBytes8(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes8 result)
    {
        for (uint256 k; k < 8; ++k) {
            result |= bytes8(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 9 bytes of `b` at `offset`.
    function readBytes9(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes9 result)
    {
        for (uint256 k; k < 9; ++k) {
            result |= bytes9(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 10 bytes of `b` at `offset`.
    function readBytes10(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes10 result)
    {
        for (uint256 k; k < 10; ++k) {
            result |= bytes10(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 11 bytes of `b` at `offset`.
    function readBytes11(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes11 result)
    {
        for (uint256 k; k < 11; ++k) {
            result |= bytes11(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 12 bytes of `b` at `offset`.
    function readBytes12(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes12 result)
    {
        for (uint256 k; k < 12; ++k) {
            result |= bytes12(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 13 bytes of `b` at `offset`.
    function readBytes13(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes13 result)
    {
        for (uint256 k; k < 13; ++k) {
            result |= bytes13(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 14 bytes of `b` at `offset`.
    function readBytes14(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes14 result)
    {
        for (uint256 k; k < 14; ++k) {
            result |= bytes14(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 15 bytes of `b` at `offset`.
    function readBytes15(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes15 result)
    {
        for (uint256 k; k < 15; ++k) {
            result |= bytes15(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 16 bytes of `b` at `offset`.
    function readBytes16(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes16 result)
    {
        for (uint256 k; k < 16; ++k) {
            result |= bytes16(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 17 bytes of `b` at `offset`.
    function readBytes17(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes17 result)
    {
        for (uint256 k; k < 17; ++k) {
            result |= bytes17(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 18 bytes of `b` at `offset`.
    function readBytes18(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes18 result)
    {
        for (uint256 k; k < 18; ++k) {
            result |= bytes18(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 19 bytes of `b` at `offset`.
    function readBytes19(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes19 result)
    {
        for (uint256 k; k < 19; ++k) {
            result |= bytes19(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 20 bytes of `b` at `offset`.
    function readBytes20(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes20 result)
    {
        for (uint256 k; k < 20; ++k) {
            result |= bytes20(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 21 bytes of `b` at `offset`.
    function readBytes21(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes21 result)
    {
        for (uint256 k; k < 21; ++k) {
            result |= bytes21(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 22 bytes of `b` at `offset`.
    function readBytes22(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes22 result)
    {
        for (uint256 k; k < 22; ++k) {
            result |= bytes22(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 23 bytes of `b` at `offset`.
    function readBytes23(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes23 result)
    {
        for (uint256 k; k < 23; ++k) {
            result |= bytes23(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 24 bytes of `b` at `offset`.
    function readBytes24(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes24 result)
    {
        for (uint256 k; k < 24; ++k) {
            result |= bytes24(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 25 bytes of `b` at `offset`.
    function readBytes25(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes25 result)
    {
        for (uint256 k; k < 25; ++k) {
            result |= bytes25(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 26 bytes of `b` at `offset`.
    function readBytes26(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes26 result)
    {
        for (uint256 k; k < 26; ++k) {
            result |= bytes26(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 27 bytes of `b` at `offset`.
    function readBytes27(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes27 result)
    {
        for (uint256 k; k < 27; ++k) {
            result |= bytes27(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 28 bytes of `b` at `offset`.
    function readBytes28(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes28 result)
    {
        for (uint256 k; k < 28; ++k) {
            result |= bytes28(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 29 bytes of `b` at `offset`.
    function readBytes29(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes29 result)
    {
        for (uint256 k; k < 29; ++k) {
            result |= bytes29(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 30 bytes of `b` at `offset`.
    function readBytes30(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes30 result)
    {
        for (uint256 k; k < 30; ++k) {
            result |= bytes30(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 31 bytes of `b` at `offset`.
    function readBytes31(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes31 result)
    {
        for (uint256 k; k < 31; ++k) {
            result |= bytes31(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 32 bytes of `b` at `offset`.
    function readBytes32(bytes memory b, uint256 offset)
        internal
        pure
        returns (bytes32 result)
    {
        for (uint256 k; k < 32; ++k) {
            result |= bytes32(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 32 bytes of `b` at `offset`, read as a big-endian integer.
    function readUint256BE(bytes memory b, uint256 offset) internal pure returns (uint256 result) {
        for (uint256 k; k < 32; ++k) {
            result = (result << 8) | uint8(b[offset + k]);
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes1(bytes memory b, uint256 offset, bytes1 value) internal pure {
        for (uint256 k; k < 1; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes2(bytes memory b, uint256 offset, bytes2 value) internal pure {
        for (uint256 k; k < 2; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes3(bytes memory b, uint256 offset, bytes3 value) internal pure {
        for (uint256 k; k < 3; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes4(bytes memory b, uint256 offset, bytes4 value) internal pure {
        for (uint256 k; k < 4; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes5(bytes memory b, uint256 offset, bytes5 value) internal pure {
        for (uint256 k; k < 5; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes6(bytes memory b, uint256 offset, bytes6 value) internal pure {
        for (uint256 k; k < 6; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes7(bytes memory b, uint256 offset, bytes7 value) internal pure {
        for (uint256 k; k < 7; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes8(bytes memory b, uint256 offset, bytes8 value) internal pure {
        for (uint256 k; k < 8; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes9(bytes memory b, uint256 offset, bytes9 value) internal pure {
        for (uint256 k; k < 9; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes10(bytes memory b, uint256 offset, bytes10 value) internal pure {
        for (uint256 k; k < 10; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes11(bytes memory b, uint256 offset, bytes11 value) internal pure {
        for (uint256 k; k < 11; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes12(bytes memory b, uint256 offset, bytes12 value) internal pure {
        for (uint256 k; k < 12; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes13(bytes memory b, uint256 offset, bytes13 value) internal pure {
        for (uint256 k; k < 13; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes14(bytes memory b, uint256 offset, bytes14 value) internal pure {
        for (uint256 k; k < 14; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes15(bytes memory b, uint256 offset, bytes15 value) internal pure {
        for (uint256 k; k < 15; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes16(bytes memory b, uint256 offset, bytes16 value) internal pure {
        for (uint256 k; k < 16; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes17(bytes memory b, uint256 offset, bytes17 value) internal pure {
        for (uint256 k; k < 17; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes18(bytes memory b, uint256 offset, bytes18 value) internal pure {
        for (uint256 k; k < 18; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes19(bytes memory b, uint256 offset, bytes19 value) internal pure {
        for (uint256 k; k < 19; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes20(bytes memory b, uint256 offset, bytes20 value) internal pure {
        for (uint256 k; k < 20; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes21(bytes memory b, uint256 offset, bytes21 value) internal pure {
        for (uint256 k; k < 21; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes22(bytes memory b, uint256 offset, bytes22 value) internal pure {
        for (uint256 k; k < 22; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes23(bytes memory b, uint256 offset, bytes23 value) internal pure {
        for (uint256 k; k < 23; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes24(bytes memory b, uint256 offset, bytes24 value) internal pure {
        for (uint256 k; k < 24; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes25(bytes memory b, uint256 offset, bytes25 value) internal pure {
        for (uint256 k; k < 25; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes26(bytes memory b, uint256 offset, bytes26 value) internal pure {
        for (uint256 k; k < 26; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes27(bytes memory b, uint256 offset, bytes27 value) internal pure {
        for (uint256 k; k < 27; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes28(bytes memory b, uint256 offset, bytes28 value) internal pure {
        for (uint256 k; k < 28; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes29(bytes memory b, uint256 offset, bytes29 value) internal pure {
        for (uint256 k; k < 29; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes30(bytes memory b, uint256 offset, bytes30 value) internal pure {
        for (uint256 k; k < 30; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes31(bytes memory b, uint256 offset, bytes31 value) internal pure {
        for (uint256 k; k < 31; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev Writes `value` into `b` at `offset`.
    function writeBytes32(bytes memory b, uint256 offset, bytes32 value) internal pure {
        for (uint256 k; k < 32; ++k) {
            b[offset + k] = value[k];
        }
    }

    /// @dev The 1 byte of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes1(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes1 result)
    {
        if (offset > b.length || b.length - offset < 1) return (false, bytes1(0));
        return (true, readBytes1(b, offset));
    }

    /// @dev The 2 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes2(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes2 result)
    {
        if (offset > b.length || b.length - offset < 2) return (false, bytes2(0));
        return (true, readBytes2(b, offset));
    }

    /// @dev The 3 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes3(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes3 result)
    {
        if (offset > b.length || b.length - offset < 3) return (false, bytes3(0));
        return (true, readBytes3(b, offset));
    }

    /// @dev The 4 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes4(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes4 result)
    {
        if (offset > b.length || b.length - offset < 4) return (false, bytes4(0));
        return (true, readBytes4(b, offset));
    }

    /// @dev The 5 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes5(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes5 result)
    {
        if (offset > b.length || b.length - offset < 5) return (false, bytes5(0));
        return (true, readBytes5(b, offset));
    }

    /// @dev The 6 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes6(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes6 result)
    {
        if (offset > b.length || b.length - offset < 6) return (false, bytes6(0));
        return (true, readBytes6(b, offset));
    }

    /// @dev The 7 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes7(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes7 result)
    {
        if (offset > b.length || b.length - offset < 7) return (false, bytes7(0));
        return (true, readBytes7(b, offset));
    }

    /// @dev The 8 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes8(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes8 result)
    {
        if (offset > b.length || b.length - offset < 8) return (false, bytes8(0));
        return (true, readBytes8(b, offset));
    }

    /// @dev The 9 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes9(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes9 result)
    {
        if (offset > b.length || b.length - offset < 9) return (false, bytes9(0));
        return (true, readBytes9(b, offset));
    }

    /// @dev The 10 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes10(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes10 result)
    {
        if (offset > b.length || b.length - offset < 10) return (false, bytes10(0));
        return (true, readBytes10(b, offset));
    }

    /// @dev The 11 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes11(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes11 result)
    {
        if (offset > b.length || b.length - offset < 11) return (false, bytes11(0));
        return (true, readBytes11(b, offset));
    }

    /// @dev The 12 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes12(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes12 result)
    {
        if (offset > b.length || b.length - offset < 12) return (false, bytes12(0));
        return (true, readBytes12(b, offset));
    }

    /// @dev The 13 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes13(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes13 result)
    {
        if (offset > b.length || b.length - offset < 13) return (false, bytes13(0));
        return (true, readBytes13(b, offset));
    }

    /// @dev The 14 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes14(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes14 result)
    {
        if (offset > b.length || b.length - offset < 14) return (false, bytes14(0));
        return (true, readBytes14(b, offset));
    }

    /// @dev The 15 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes15(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes15 result)
    {
        if (offset > b.length || b.length - offset < 15) return (false, bytes15(0));
        return (true, readBytes15(b, offset));
    }

    /// @dev The 16 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes16(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes16 result)
    {
        if (offset > b.length || b.length - offset < 16) return (false, bytes16(0));
        return (true, readBytes16(b, offset));
    }

    /// @dev The 17 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes17(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes17 result)
    {
        if (offset > b.length || b.length - offset < 17) return (false, bytes17(0));
        return (true, readBytes17(b, offset));
    }

    /// @dev The 18 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes18(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes18 result)
    {
        if (offset > b.length || b.length - offset < 18) return (false, bytes18(0));
        return (true, readBytes18(b, offset));
    }

    /// @dev The 19 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes19(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes19 result)
    {
        if (offset > b.length || b.length - offset < 19) return (false, bytes19(0));
        return (true, readBytes19(b, offset));
    }

    /// @dev The 20 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes20(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes20 result)
    {
        if (offset > b.length || b.length - offset < 20) return (false, bytes20(0));
        return (true, readBytes20(b, offset));
    }

    /// @dev The 21 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes21(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes21 result)
    {
        if (offset > b.length || b.length - offset < 21) return (false, bytes21(0));
        return (true, readBytes21(b, offset));
    }

    /// @dev The 22 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes22(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes22 result)
    {
        if (offset > b.length || b.length - offset < 22) return (false, bytes22(0));
        return (true, readBytes22(b, offset));
    }

    /// @dev The 23 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes23(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes23 result)
    {
        if (offset > b.length || b.length - offset < 23) return (false, bytes23(0));
        return (true, readBytes23(b, offset));
    }

    /// @dev The 24 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes24(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes24 result)
    {
        if (offset > b.length || b.length - offset < 24) return (false, bytes24(0));
        return (true, readBytes24(b, offset));
    }

    /// @dev The 25 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes25(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes25 result)
    {
        if (offset > b.length || b.length - offset < 25) return (false, bytes25(0));
        return (true, readBytes25(b, offset));
    }

    /// @dev The 26 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes26(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes26 result)
    {
        if (offset > b.length || b.length - offset < 26) return (false, bytes26(0));
        return (true, readBytes26(b, offset));
    }

    /// @dev The 27 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes27(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes27 result)
    {
        if (offset > b.length || b.length - offset < 27) return (false, bytes27(0));
        return (true, readBytes27(b, offset));
    }

    /// @dev The 28 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes28(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes28 result)
    {
        if (offset > b.length || b.length - offset < 28) return (false, bytes28(0));
        return (true, readBytes28(b, offset));
    }

    /// @dev The 29 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes29(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes29 result)
    {
        if (offset > b.length || b.length - offset < 29) return (false, bytes29(0));
        return (true, readBytes29(b, offset));
    }

    /// @dev The 30 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes30(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes30 result)
    {
        if (offset > b.length || b.length - offset < 30) return (false, bytes30(0));
        return (true, readBytes30(b, offset));
    }

    /// @dev The 31 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes31(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes31 result)
    {
        if (offset > b.length || b.length - offset < 31) return (false, bytes31(0));
        return (true, readBytes31(b, offset));
    }

    /// @dev The 32 bytes of `b` at `offset`, or `false` and zero when they do
    /// not all lie inside `b`.
    function tryReadBytes32(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, bytes32 result)
    {
        if (offset > b.length || b.length - offset < 32) return (false, bytes32(0));
        return (true, readBytes32(b, offset));
    }

    /// @dev The 32 bytes of `b` at `offset` as a big-endian integer, or `false`
    /// and zero when they do not all lie inside `b`.
    function tryReadUint256BE(bytes memory b, uint256 offset)
        internal
        pure
        returns (bool ok, uint256 result)
    {
        if (offset > b.length || b.length - offset < 32) return (false, 0);
        return (true, readUint256BE(b, offset));
    }

    /// @dev Writes `value` into `b` at `offset` as a big-endian integer.
    function writeUint256BE(bytes memory b, uint256 offset, uint256 value) internal pure {
        for (uint256 k; k < 32; ++k) {
            b[offset + k] = bytes1(uint8(value >> (248 - 8 * k)));
        }
    }

    /// @dev Copies `count` bytes from `src` at `srcOffset` to `dst` at
    /// `dstOffset`. The ranges may overlap: the result is as if the source
    /// were read in full before the first write.
    function copyInto(
        bytes memory dst,
        uint256 dstOffset,
        bytes memory src,
        uint256 srcOffset,
        uint256 count
    ) internal pure {
        // Both ranges are validated before anything is written, so a copy
        // running downwards fails on its range the way one running upwards
        // does, rather than on the arithmetic reaching its far end.
        if (
            count > dst.length || dstOffset > dst.length - count || count > src.length
                || srcOffset > src.length - count
        ) count = _outOfBounds();
        if (dstOffset > srcOffset) {
            for (uint256 k = count; k > 0; --k) {
                dst[dstOffset + k - 1] = src[srcOffset + k - 1];
            }
        } else {
            for (uint256 k; k < count; ++k) {
                dst[dstOffset + k] = src[srcOffset + k];
            }
        }
    }

    /// @dev Sets `count` bytes of `dst` at `offset` to `value`.
    function fill(bytes memory dst, uint256 offset, uint256 count, bytes1 value) internal pure {
        for (uint256 k; k < count; ++k) {
            dst[offset + k] = value;
        }
    }

    /// @dev Whether `a` and `b` have the same length and the same bytes. This
    /// is an exact comparison, a word at a time, not a comparison of hashes.
    function equals(bytes memory a, bytes memory b) internal pure returns (bool) {
        uint256 n = a.length;
        if (n != b.length) return false;
        uint256 i;
        while (i + 32 <= n) {
            if (readBytes32(a, i) != readBytes32(b, i)) return false;
            i += 32;
        }
        if (i == n) return true;
        // What is left is shorter than a word. One more word pulled back to
        // end where the input ends covers it; below a word, a byte at a time.
        if (n >= 32) return readBytes32(a, n - 32) == readBytes32(b, n - 32);
        for (; i < n; ++i) {
            if (a[i] != b[i]) return false;
        }
        return true;
    }

    /// @dev Whether the `b.length` bytes of `a` at `offset` are the bytes of
    /// `b`. Reverts with `Panic(0x32)` unless they all lie inside `a`, before
    /// comparing any byte.
    function equalsAt(bytes memory a, uint256 offset, bytes memory b) internal pure returns (bool) {
        uint256 count = b.length;
        if (offset > a.length || count > a.length - offset) offset = _outOfBounds();
        for (uint256 k; k < count; ++k) {
            if (a[offset + k] != b[k]) return false;
        }
        return true;
    }

    /// @dev A copy of the `count` bytes of `b` at `offset`. Reverts with
    /// `Panic(0x32)` unless they all lie inside `b`, before allocating.
    /// Declared under the `solar-view` custom tag, the result reads the bytes
    /// of `b` in place instead; the compiler then rejects every write to them
    /// while the view is still read, so the program behaves as if the copy
    /// were made.
    function slice(bytes memory b, uint256 offset, uint256 count)
        internal
        pure
        returns (bytes memory result)
    {
        if (offset > b.length || count > b.length - offset) offset = _outOfBounds();
        result = new bytes(count);
        for (uint256 k; k < count; ++k) {
            result[k] = b[offset + k];
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
