// SPDX-License-Identifier: MIT
// Generated by scripts/core/gen_modules.py; do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Checked fixed-width byte loads from `bytes calldata`, and bulk copy
/// out of it.
/// @dev Compiler-owned module, imported as `solar:core/v1/CalldataBytes.sol`.
/// Solidity does not let two functions differ only in the data location of a
/// parameter, so the calldata operations live here under the names `Bytes`
/// uses for memory. Every read checks that the full width lies inside the
/// slice and reverts with `Panic(0x32)` otherwise; nothing is padded.
/// `copyInto` validates both ranges before it writes. Every body here is
/// ordinary checked Solidity and defines the behaviour; the compiler lowers
/// each entry point to `calldataload` and `calldatacopy` by module identity.
library CalldataBytes {
    /// @dev The 1 byte of `b` at `offset`.
    function readBytes1(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes1 result)
    {
        for (uint256 k; k < 1; ++k) {
            result |= bytes1(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 2 bytes of `b` at `offset`.
    function readBytes2(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes2 result)
    {
        for (uint256 k; k < 2; ++k) {
            result |= bytes2(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 3 bytes of `b` at `offset`.
    function readBytes3(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes3 result)
    {
        for (uint256 k; k < 3; ++k) {
            result |= bytes3(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 4 bytes of `b` at `offset`.
    function readBytes4(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes4 result)
    {
        for (uint256 k; k < 4; ++k) {
            result |= bytes4(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 5 bytes of `b` at `offset`.
    function readBytes5(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes5 result)
    {
        for (uint256 k; k < 5; ++k) {
            result |= bytes5(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 6 bytes of `b` at `offset`.
    function readBytes6(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes6 result)
    {
        for (uint256 k; k < 6; ++k) {
            result |= bytes6(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 7 bytes of `b` at `offset`.
    function readBytes7(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes7 result)
    {
        for (uint256 k; k < 7; ++k) {
            result |= bytes7(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 8 bytes of `b` at `offset`.
    function readBytes8(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes8 result)
    {
        for (uint256 k; k < 8; ++k) {
            result |= bytes8(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 9 bytes of `b` at `offset`.
    function readBytes9(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes9 result)
    {
        for (uint256 k; k < 9; ++k) {
            result |= bytes9(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 10 bytes of `b` at `offset`.
    function readBytes10(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes10 result)
    {
        for (uint256 k; k < 10; ++k) {
            result |= bytes10(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 11 bytes of `b` at `offset`.
    function readBytes11(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes11 result)
    {
        for (uint256 k; k < 11; ++k) {
            result |= bytes11(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 12 bytes of `b` at `offset`.
    function readBytes12(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes12 result)
    {
        for (uint256 k; k < 12; ++k) {
            result |= bytes12(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 13 bytes of `b` at `offset`.
    function readBytes13(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes13 result)
    {
        for (uint256 k; k < 13; ++k) {
            result |= bytes13(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 14 bytes of `b` at `offset`.
    function readBytes14(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes14 result)
    {
        for (uint256 k; k < 14; ++k) {
            result |= bytes14(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 15 bytes of `b` at `offset`.
    function readBytes15(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes15 result)
    {
        for (uint256 k; k < 15; ++k) {
            result |= bytes15(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 16 bytes of `b` at `offset`.
    function readBytes16(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes16 result)
    {
        for (uint256 k; k < 16; ++k) {
            result |= bytes16(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 17 bytes of `b` at `offset`.
    function readBytes17(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes17 result)
    {
        for (uint256 k; k < 17; ++k) {
            result |= bytes17(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 18 bytes of `b` at `offset`.
    function readBytes18(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes18 result)
    {
        for (uint256 k; k < 18; ++k) {
            result |= bytes18(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 19 bytes of `b` at `offset`.
    function readBytes19(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes19 result)
    {
        for (uint256 k; k < 19; ++k) {
            result |= bytes19(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 20 bytes of `b` at `offset`.
    function readBytes20(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes20 result)
    {
        for (uint256 k; k < 20; ++k) {
            result |= bytes20(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 21 bytes of `b` at `offset`.
    function readBytes21(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes21 result)
    {
        for (uint256 k; k < 21; ++k) {
            result |= bytes21(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 22 bytes of `b` at `offset`.
    function readBytes22(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes22 result)
    {
        for (uint256 k; k < 22; ++k) {
            result |= bytes22(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 23 bytes of `b` at `offset`.
    function readBytes23(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes23 result)
    {
        for (uint256 k; k < 23; ++k) {
            result |= bytes23(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 24 bytes of `b` at `offset`.
    function readBytes24(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes24 result)
    {
        for (uint256 k; k < 24; ++k) {
            result |= bytes24(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 25 bytes of `b` at `offset`.
    function readBytes25(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes25 result)
    {
        for (uint256 k; k < 25; ++k) {
            result |= bytes25(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 26 bytes of `b` at `offset`.
    function readBytes26(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes26 result)
    {
        for (uint256 k; k < 26; ++k) {
            result |= bytes26(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 27 bytes of `b` at `offset`.
    function readBytes27(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes27 result)
    {
        for (uint256 k; k < 27; ++k) {
            result |= bytes27(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 28 bytes of `b` at `offset`.
    function readBytes28(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes28 result)
    {
        for (uint256 k; k < 28; ++k) {
            result |= bytes28(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 29 bytes of `b` at `offset`.
    function readBytes29(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes29 result)
    {
        for (uint256 k; k < 29; ++k) {
            result |= bytes29(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 30 bytes of `b` at `offset`.
    function readBytes30(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes30 result)
    {
        for (uint256 k; k < 30; ++k) {
            result |= bytes30(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 31 bytes of `b` at `offset`.
    function readBytes31(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes31 result)
    {
        for (uint256 k; k < 31; ++k) {
            result |= bytes31(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 32 bytes of `b` at `offset`.
    function readBytes32(bytes calldata b, uint256 offset)
        internal
        pure
        returns (bytes32 result)
    {
        for (uint256 k; k < 32; ++k) {
            result |= bytes32(b[offset + k]) >> (8 * k);
        }
    }

    /// @dev The 32 bytes of `b` at `offset`, read as a big-endian integer.
    function readUint256BE(bytes calldata b, uint256 offset) internal pure returns (uint256 result) {
        for (uint256 k; k < 32; ++k) {
            result = (result << 8) | uint8(b[offset + k]);
        }
    }

    /// @dev Copies `count` bytes of `src` at `srcOffset` into `dst` at
    /// `dstOffset`.
    function copyInto(
        bytes memory dst,
        uint256 dstOffset,
        bytes calldata src,
        uint256 srcOffset,
        uint256 count
    ) internal pure {
        // Both ranges are validated before anything is written.
        if (
            count > dst.length || dstOffset > dst.length - count || count > src.length
                || srcOffset > src.length - count
        ) count = _outOfBounds();
        for (uint256 k; k < count; ++k) {
            dst[dstOffset + k] = src[srcOffset + k];
        }
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
