// SPDX-License-Identifier: MIT
// Generated by scripts/core/gen_modules.py; do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Narrowing casts that fail instead of truncating.
/// @dev Compiler-owned module, imported as `solar:core/v1/Cast.sol`. A
/// Solidity cast such as `uint40(x)` keeps the low bits and drops the rest
/// without a word; these revert with `Panic(0x11)`, the arithmetic overflow
/// panic, when `x` does not fit the target type, and otherwise return it
/// unchanged. Casts that cannot lose anything are not here: write them as
/// ordinary conversions.
library Cast {
    /// @dev `x` as a `uint8`.
    function toUint8(uint256 x) internal pure returns (uint8) {
        if (x > type(uint8).max) _overflow();
        return uint8(x);
    }

    /// @dev `x` as a `uint16`.
    function toUint16(uint256 x) internal pure returns (uint16) {
        if (x > type(uint16).max) _overflow();
        return uint16(x);
    }

    /// @dev `x` as a `uint24`.
    function toUint24(uint256 x) internal pure returns (uint24) {
        if (x > type(uint24).max) _overflow();
        return uint24(x);
    }

    /// @dev `x` as a `uint32`.
    function toUint32(uint256 x) internal pure returns (uint32) {
        if (x > type(uint32).max) _overflow();
        return uint32(x);
    }

    /// @dev `x` as a `uint40`.
    function toUint40(uint256 x) internal pure returns (uint40) {
        if (x > type(uint40).max) _overflow();
        return uint40(x);
    }

    /// @dev `x` as a `uint48`.
    function toUint48(uint256 x) internal pure returns (uint48) {
        if (x > type(uint48).max) _overflow();
        return uint48(x);
    }

    /// @dev `x` as a `uint56`.
    function toUint56(uint256 x) internal pure returns (uint56) {
        if (x > type(uint56).max) _overflow();
        return uint56(x);
    }

    /// @dev `x` as a `uint64`.
    function toUint64(uint256 x) internal pure returns (uint64) {
        if (x > type(uint64).max) _overflow();
        return uint64(x);
    }

    /// @dev `x` as a `uint72`.
    function toUint72(uint256 x) internal pure returns (uint72) {
        if (x > type(uint72).max) _overflow();
        return uint72(x);
    }

    /// @dev `x` as a `uint80`.
    function toUint80(uint256 x) internal pure returns (uint80) {
        if (x > type(uint80).max) _overflow();
        return uint80(x);
    }

    /// @dev `x` as a `uint88`.
    function toUint88(uint256 x) internal pure returns (uint88) {
        if (x > type(uint88).max) _overflow();
        return uint88(x);
    }

    /// @dev `x` as a `uint96`.
    function toUint96(uint256 x) internal pure returns (uint96) {
        if (x > type(uint96).max) _overflow();
        return uint96(x);
    }

    /// @dev `x` as a `uint104`.
    function toUint104(uint256 x) internal pure returns (uint104) {
        if (x > type(uint104).max) _overflow();
        return uint104(x);
    }

    /// @dev `x` as a `uint112`.
    function toUint112(uint256 x) internal pure returns (uint112) {
        if (x > type(uint112).max) _overflow();
        return uint112(x);
    }

    /// @dev `x` as a `uint120`.
    function toUint120(uint256 x) internal pure returns (uint120) {
        if (x > type(uint120).max) _overflow();
        return uint120(x);
    }

    /// @dev `x` as a `uint128`.
    function toUint128(uint256 x) internal pure returns (uint128) {
        if (x > type(uint128).max) _overflow();
        return uint128(x);
    }

    /// @dev `x` as a `uint136`.
    function toUint136(uint256 x) internal pure returns (uint136) {
        if (x > type(uint136).max) _overflow();
        return uint136(x);
    }

    /// @dev `x` as a `uint144`.
    function toUint144(uint256 x) internal pure returns (uint144) {
        if (x > type(uint144).max) _overflow();
        return uint144(x);
    }

    /// @dev `x` as a `uint152`.
    function toUint152(uint256 x) internal pure returns (uint152) {
        if (x > type(uint152).max) _overflow();
        return uint152(x);
    }

    /// @dev `x` as a `uint160`.
    function toUint160(uint256 x) internal pure returns (uint160) {
        if (x > type(uint160).max) _overflow();
        return uint160(x);
    }

    /// @dev `x` as a `uint168`.
    function toUint168(uint256 x) internal pure returns (uint168) {
        if (x > type(uint168).max) _overflow();
        return uint168(x);
    }

    /// @dev `x` as a `uint176`.
    function toUint176(uint256 x) internal pure returns (uint176) {
        if (x > type(uint176).max) _overflow();
        return uint176(x);
    }

    /// @dev `x` as a `uint184`.
    function toUint184(uint256 x) internal pure returns (uint184) {
        if (x > type(uint184).max) _overflow();
        return uint184(x);
    }

    /// @dev `x` as a `uint192`.
    function toUint192(uint256 x) internal pure returns (uint192) {
        if (x > type(uint192).max) _overflow();
        return uint192(x);
    }

    /// @dev `x` as a `uint200`.
    function toUint200(uint256 x) internal pure returns (uint200) {
        if (x > type(uint200).max) _overflow();
        return uint200(x);
    }

    /// @dev `x` as a `uint208`.
    function toUint208(uint256 x) internal pure returns (uint208) {
        if (x > type(uint208).max) _overflow();
        return uint208(x);
    }

    /// @dev `x` as a `uint216`.
    function toUint216(uint256 x) internal pure returns (uint216) {
        if (x > type(uint216).max) _overflow();
        return uint216(x);
    }

    /// @dev `x` as a `uint224`.
    function toUint224(uint256 x) internal pure returns (uint224) {
        if (x > type(uint224).max) _overflow();
        return uint224(x);
    }

    /// @dev `x` as a `uint232`.
    function toUint232(uint256 x) internal pure returns (uint232) {
        if (x > type(uint232).max) _overflow();
        return uint232(x);
    }

    /// @dev `x` as a `uint240`.
    function toUint240(uint256 x) internal pure returns (uint240) {
        if (x > type(uint240).max) _overflow();
        return uint240(x);
    }

    /// @dev `x` as a `uint248`.
    function toUint248(uint256 x) internal pure returns (uint248) {
        if (x > type(uint248).max) _overflow();
        return uint248(x);
    }

    /// @dev `x` as an `int8`.
    function toInt8(int256 x) internal pure returns (int8) {
        if (x < type(int8).min || x > type(int8).max) _overflow();
        return int8(x);
    }

    /// @dev `x` as an `int16`.
    function toInt16(int256 x) internal pure returns (int16) {
        if (x < type(int16).min || x > type(int16).max) _overflow();
        return int16(x);
    }

    /// @dev `x` as an `int24`.
    function toInt24(int256 x) internal pure returns (int24) {
        if (x < type(int24).min || x > type(int24).max) _overflow();
        return int24(x);
    }

    /// @dev `x` as an `int32`.
    function toInt32(int256 x) internal pure returns (int32) {
        if (x < type(int32).min || x > type(int32).max) _overflow();
        return int32(x);
    }

    /// @dev `x` as an `int40`.
    function toInt40(int256 x) internal pure returns (int40) {
        if (x < type(int40).min || x > type(int40).max) _overflow();
        return int40(x);
    }

    /// @dev `x` as an `int48`.
    function toInt48(int256 x) internal pure returns (int48) {
        if (x < type(int48).min || x > type(int48).max) _overflow();
        return int48(x);
    }

    /// @dev `x` as an `int56`.
    function toInt56(int256 x) internal pure returns (int56) {
        if (x < type(int56).min || x > type(int56).max) _overflow();
        return int56(x);
    }

    /// @dev `x` as an `int64`.
    function toInt64(int256 x) internal pure returns (int64) {
        if (x < type(int64).min || x > type(int64).max) _overflow();
        return int64(x);
    }

    /// @dev `x` as an `int72`.
    function toInt72(int256 x) internal pure returns (int72) {
        if (x < type(int72).min || x > type(int72).max) _overflow();
        return int72(x);
    }

    /// @dev `x` as an `int80`.
    function toInt80(int256 x) internal pure returns (int80) {
        if (x < type(int80).min || x > type(int80).max) _overflow();
        return int80(x);
    }

    /// @dev `x` as an `int88`.
    function toInt88(int256 x) internal pure returns (int88) {
        if (x < type(int88).min || x > type(int88).max) _overflow();
        return int88(x);
    }

    /// @dev `x` as an `int96`.
    function toInt96(int256 x) internal pure returns (int96) {
        if (x < type(int96).min || x > type(int96).max) _overflow();
        return int96(x);
    }

    /// @dev `x` as an `int104`.
    function toInt104(int256 x) internal pure returns (int104) {
        if (x < type(int104).min || x > type(int104).max) _overflow();
        return int104(x);
    }

    /// @dev `x` as an `int112`.
    function toInt112(int256 x) internal pure returns (int112) {
        if (x < type(int112).min || x > type(int112).max) _overflow();
        return int112(x);
    }

    /// @dev `x` as an `int120`.
    function toInt120(int256 x) internal pure returns (int120) {
        if (x < type(int120).min || x > type(int120).max) _overflow();
        return int120(x);
    }

    /// @dev `x` as an `int128`.
    function toInt128(int256 x) internal pure returns (int128) {
        if (x < type(int128).min || x > type(int128).max) _overflow();
        return int128(x);
    }

    /// @dev `x` as an `int136`.
    function toInt136(int256 x) internal pure returns (int136) {
        if (x < type(int136).min || x > type(int136).max) _overflow();
        return int136(x);
    }

    /// @dev `x` as an `int144`.
    function toInt144(int256 x) internal pure returns (int144) {
        if (x < type(int144).min || x > type(int144).max) _overflow();
        return int144(x);
    }

    /// @dev `x` as an `int152`.
    function toInt152(int256 x) internal pure returns (int152) {
        if (x < type(int152).min || x > type(int152).max) _overflow();
        return int152(x);
    }

    /// @dev `x` as an `int160`.
    function toInt160(int256 x) internal pure returns (int160) {
        if (x < type(int160).min || x > type(int160).max) _overflow();
        return int160(x);
    }

    /// @dev `x` as an `int168`.
    function toInt168(int256 x) internal pure returns (int168) {
        if (x < type(int168).min || x > type(int168).max) _overflow();
        return int168(x);
    }

    /// @dev `x` as an `int176`.
    function toInt176(int256 x) internal pure returns (int176) {
        if (x < type(int176).min || x > type(int176).max) _overflow();
        return int176(x);
    }

    /// @dev `x` as an `int184`.
    function toInt184(int256 x) internal pure returns (int184) {
        if (x < type(int184).min || x > type(int184).max) _overflow();
        return int184(x);
    }

    /// @dev `x` as an `int192`.
    function toInt192(int256 x) internal pure returns (int192) {
        if (x < type(int192).min || x > type(int192).max) _overflow();
        return int192(x);
    }

    /// @dev `x` as an `int200`.
    function toInt200(int256 x) internal pure returns (int200) {
        if (x < type(int200).min || x > type(int200).max) _overflow();
        return int200(x);
    }

    /// @dev `x` as an `int208`.
    function toInt208(int256 x) internal pure returns (int208) {
        if (x < type(int208).min || x > type(int208).max) _overflow();
        return int208(x);
    }

    /// @dev `x` as an `int216`.
    function toInt216(int256 x) internal pure returns (int216) {
        if (x < type(int216).min || x > type(int216).max) _overflow();
        return int216(x);
    }

    /// @dev `x` as an `int224`.
    function toInt224(int256 x) internal pure returns (int224) {
        if (x < type(int224).min || x > type(int224).max) _overflow();
        return int224(x);
    }

    /// @dev `x` as an `int232`.
    function toInt232(int256 x) internal pure returns (int232) {
        if (x < type(int232).min || x > type(int232).max) _overflow();
        return int232(x);
    }

    /// @dev `x` as an `int240`.
    function toInt240(int256 x) internal pure returns (int240) {
        if (x < type(int240).min || x > type(int240).max) _overflow();
        return int240(x);
    }

    /// @dev `x` as an `int248`.
    function toInt248(int256 x) internal pure returns (int248) {
        if (x < type(int248).min || x > type(int248).max) _overflow();
        return int248(x);
    }

    /// @dev `x` as an `int256`.
    function toInt256(uint256 x) internal pure returns (int256) {
        if (x > uint256(type(int256).max)) _overflow();
        return int256(x);
    }

    /// @dev `x` as a `uint256`.
    function toUint256(int256 x) internal pure returns (uint256) {
        if (x < 0) _overflow();
        return uint256(x);
    }

    /// @dev Raises the `Panic(0x11)` a checked addition raises, which is the
    /// portable spelling of a value that does not fit.
    function _overflow() private pure {
        uint256 most = type(uint256).max;
        most += 1;
    }
}
