// SPDX-License-Identifier: MIT
// Generated by scripts/core/gen_modules.py; do not edit by hand.
pragma solidity ^0.8.20;

import {Arrays} from "solar:core/v1/Arrays.sol";

/// @notice Checked algorithms over one-word dynamic memory arrays.
/// @dev Compiler-owned module, imported as `solar:core/v1/WordArrays.sol`.
/// The bodies are portable checked Solidity and define the behavior; Solar
/// lowers every overload to one shared implementation by module identity.
library WordArrays {
    /// @dev Sorts `a` in ascending order.
    function sort(uint256[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            uint256 value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(uint256[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(a[i]), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(uint256[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

    /// @dev Sorts `a` in ascending order.
    function sort(int256[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            int256 value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(int256[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(a[i]), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(int256[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

    /// @dev Sorts `a` in ascending order.
    function sort(address[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            address value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(address[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(uint160(a[i])), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(address[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

    /// @dev Sorts `a` in ascending order.
    function sort(bytes32[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            bytes32 value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(bytes32[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(a[i]), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(bytes32[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

}
