// SPDX-License-Identifier: MIT
// Generated by scripts/core/gen_modules.py; do not edit by hand.
pragma solidity ^0.8.20;

import {Arrays} from "solar:core/v1/Arrays.sol";

/// @notice Checked algorithms over one-word dynamic memory arrays.
/// @dev Compiler-owned module, imported as `solar:core/v1/WordArrays.sol`.
/// The bodies are portable checked Solidity and define the behavior; Solar
/// lowers every overload to one shared implementation by module identity.
library WordArrays {
    /// @dev Sorts `a` in ascending order.
    function sort(uint256[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            uint256 value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(uint256[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(a[i]), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(uint256[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

    /// @dev The sorted union of sorted, duplicate-free `a` and `b`.
    function union(uint256[] memory a, uint256[] memory b)
        internal
        pure
        returns (uint256[] memory c)
    {
        c = new uint256[](a.length + b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            uint256 u = a[i];
            uint256 v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                c[k] = v;
                ++k;
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        while (j < b.length) {
            c[k] = b[j];
            ++k;
            ++j;
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted intersection of sorted, duplicate-free `a` and `b`.
    function intersection(uint256[] memory a, uint256[] memory b)
        internal
        pure
        returns (uint256[] memory c)
    {
        c = new uint256[](a.length < b.length ? a.length : b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            uint256 u = a[i];
            uint256 v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                ++i;
            }
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted difference of sorted, duplicate-free `a` and `b`.
    function difference(uint256[] memory a, uint256[] memory b)
        internal
        pure
        returns (uint256[] memory c)
    {
        c = new uint256[](a.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            uint256 u = a[i];
            uint256 v = b[j];
            if (u == v) {
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        Arrays.truncate(c, k);
    }

    /// @dev Sorts `keys` by their word values with `values` moved alongside,
    /// keeps one of each key, and gives it the sum of the values its copies had.
    /// Both arrays shrink to the kept keys. The arrays must have one length, and
    /// every sum must fit a word.
    function groupSum(uint256[] memory keys, uint256[] memory values) internal pure {
        uint256 n = keys.length;
        if (values.length != n) n = _outOfBounds();
        if (n < 2) return;
        for (uint256 i = 1; i < n; ++i) {
            uint256 key = keys[i];
            uint256 value = values[i];
            uint256 j = i;
            while (j != 0 && keys[j - 1] > key) {
                keys[j] = keys[j - 1];
                values[j] = values[j - 1];
                --j;
            }
            keys[j] = key;
            values[j] = value;
        }
        uint256 kept = 0;
        uint256 sum = values[0];
        for (uint256 i = 1; i < n; ++i) {
            if (keys[i] == keys[kept]) {
                sum += values[i];
            } else {
                values[kept] = sum;
                keys[++kept] = keys[i];
                sum = values[i];
            }
        }
        values[kept] = sum;
        Arrays.truncate(keys, kept + 1);
        Arrays.truncate(values, kept + 1);
    }

    /// @dev Sorts `a` in ascending order.
    function sort(int256[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            int256 value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(int256[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(a[i]), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(int256[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

    /// @dev The sorted union of sorted, duplicate-free `a` and `b`.
    function union(int256[] memory a, int256[] memory b)
        internal
        pure
        returns (int256[] memory c)
    {
        c = new int256[](a.length + b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            int256 u = a[i];
            int256 v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                c[k] = v;
                ++k;
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        while (j < b.length) {
            c[k] = b[j];
            ++k;
            ++j;
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted intersection of sorted, duplicate-free `a` and `b`.
    function intersection(int256[] memory a, int256[] memory b)
        internal
        pure
        returns (int256[] memory c)
    {
        c = new int256[](a.length < b.length ? a.length : b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            int256 u = a[i];
            int256 v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                ++i;
            }
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted difference of sorted, duplicate-free `a` and `b`.
    function difference(int256[] memory a, int256[] memory b)
        internal
        pure
        returns (int256[] memory c)
    {
        c = new int256[](a.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            int256 u = a[i];
            int256 v = b[j];
            if (u == v) {
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        Arrays.truncate(c, k);
    }

    /// @dev Sorts `keys` by their word values with `values` moved alongside,
    /// keeps one of each key, and gives it the sum of the values its copies had.
    /// Both arrays shrink to the kept keys. The arrays must have one length, and
    /// every sum must fit a word.
    function groupSum(int256[] memory keys, uint256[] memory values) internal pure {
        uint256 n = keys.length;
        if (values.length != n) n = _outOfBounds();
        if (n < 2) return;
        for (uint256 i = 1; i < n; ++i) {
            int256 key = keys[i];
            uint256 value = values[i];
            uint256 j = i;
            while (j != 0 && uint256(keys[j - 1]) > uint256(key)) {
                keys[j] = keys[j - 1];
                values[j] = values[j - 1];
                --j;
            }
            keys[j] = key;
            values[j] = value;
        }
        uint256 kept = 0;
        uint256 sum = values[0];
        for (uint256 i = 1; i < n; ++i) {
            if (keys[i] == keys[kept]) {
                sum += values[i];
            } else {
                values[kept] = sum;
                keys[++kept] = keys[i];
                sum = values[i];
            }
        }
        values[kept] = sum;
        Arrays.truncate(keys, kept + 1);
        Arrays.truncate(values, kept + 1);
    }

    /// @dev Sorts `a` in ascending order.
    function sort(address[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            address value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(address[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(uint160(a[i])), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(address[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

    /// @dev The sorted union of sorted, duplicate-free `a` and `b`.
    function union(address[] memory a, address[] memory b)
        internal
        pure
        returns (address[] memory c)
    {
        c = new address[](a.length + b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            address u = a[i];
            address v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                c[k] = v;
                ++k;
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        while (j < b.length) {
            c[k] = b[j];
            ++k;
            ++j;
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted intersection of sorted, duplicate-free `a` and `b`.
    function intersection(address[] memory a, address[] memory b)
        internal
        pure
        returns (address[] memory c)
    {
        c = new address[](a.length < b.length ? a.length : b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            address u = a[i];
            address v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                ++i;
            }
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted difference of sorted, duplicate-free `a` and `b`.
    function difference(address[] memory a, address[] memory b)
        internal
        pure
        returns (address[] memory c)
    {
        c = new address[](a.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            address u = a[i];
            address v = b[j];
            if (u == v) {
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        Arrays.truncate(c, k);
    }

    /// @dev Sorts `keys` by their word values with `values` moved alongside,
    /// keeps one of each key, and gives it the sum of the values its copies had.
    /// Both arrays shrink to the kept keys. The arrays must have one length, and
    /// every sum must fit a word.
    function groupSum(address[] memory keys, uint256[] memory values) internal pure {
        uint256 n = keys.length;
        if (values.length != n) n = _outOfBounds();
        if (n < 2) return;
        for (uint256 i = 1; i < n; ++i) {
            address key = keys[i];
            uint256 value = values[i];
            uint256 j = i;
            while (j != 0 && keys[j - 1] > key) {
                keys[j] = keys[j - 1];
                values[j] = values[j - 1];
                --j;
            }
            keys[j] = key;
            values[j] = value;
        }
        uint256 kept = 0;
        uint256 sum = values[0];
        for (uint256 i = 1; i < n; ++i) {
            if (keys[i] == keys[kept]) {
                sum += values[i];
            } else {
                values[kept] = sum;
                keys[++kept] = keys[i];
                sum = values[i];
            }
        }
        values[kept] = sum;
        Arrays.truncate(keys, kept + 1);
        Arrays.truncate(values, kept + 1);
    }

    /// @dev Sorts `a` in ascending order.
    function sort(bytes32[] memory a) internal pure {
        for (uint256 i = 1; i < a.length; ++i) {
            bytes32 value = a[i];
            uint256 j = i;
            while (j != 0 && a[j - 1] > value) {
                a[j] = a[j - 1];
                --j;
            }
            a[j] = value;
        }
    }

    /// @dev Whether `a` contains the same value at two indices.
    function hasDuplicate(bytes32[] memory a) internal pure returns (bool) {
        if (a.length < 2) return false;
        uint256 capacity = 1;
        while (capacity < a.length * 2) capacity *= 2;
        uint256[] memory seen = new uint256[](capacity);
        uint256 mask = capacity - 1;
        for (uint256 i = a.length; i != 0;) {
            --i;
            uint256 slot =
                mulmod(uint256(a[i]), 0x100000000000000000000000000000051, ~uint256(0xbc)) & mask;
            while (seen[slot] != 0) {
                if (a[seen[slot] - 1] == a[i]) return true;
                slot = (slot + 1) & mask;
            }
            seen[slot] = i + 1;
        }
        return false;
    }

    /// @dev Removes adjacent duplicates from sorted `a` in place.
    function uniquifySorted(bytes32[] memory a) internal pure {
        if (a.length < 2) return;
        uint256 write = 1;
        for (uint256 read = 1; read < a.length; ++read) {
            if (a[read] != a[write - 1]) a[write++] = a[read];
        }
        Arrays.truncate(a, write);
    }

    /// @dev The sorted union of sorted, duplicate-free `a` and `b`.
    function union(bytes32[] memory a, bytes32[] memory b)
        internal
        pure
        returns (bytes32[] memory c)
    {
        c = new bytes32[](a.length + b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            bytes32 u = a[i];
            bytes32 v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                c[k] = v;
                ++k;
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        while (j < b.length) {
            c[k] = b[j];
            ++k;
            ++j;
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted intersection of sorted, duplicate-free `a` and `b`.
    function intersection(bytes32[] memory a, bytes32[] memory b)
        internal
        pure
        returns (bytes32[] memory c)
    {
        c = new bytes32[](a.length < b.length ? a.length : b.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            bytes32 u = a[i];
            bytes32 v = b[j];
            if (u == v) {
                c[k] = u;
                ++k;
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                ++i;
            }
        }
        Arrays.truncate(c, k);
    }

    /// @dev The sorted difference of sorted, duplicate-free `a` and `b`.
    function difference(bytes32[] memory a, bytes32[] memory b)
        internal
        pure
        returns (bytes32[] memory c)
    {
        c = new bytes32[](a.length);
        uint256 i;
        uint256 j;
        uint256 k;
        while (i < a.length && j < b.length) {
            bytes32 u = a[i];
            bytes32 v = b[j];
            if (u == v) {
                ++i;
                ++j;
            } else if (u > v) {
                ++j;
            } else {
                c[k] = u;
                ++k;
                ++i;
            }
        }
        while (i < a.length) {
            c[k] = a[i];
            ++k;
            ++i;
        }
        Arrays.truncate(c, k);
    }

    /// @dev Sorts `keys` by their word values with `values` moved alongside,
    /// keeps one of each key, and gives it the sum of the values its copies had.
    /// Both arrays shrink to the kept keys. The arrays must have one length, and
    /// every sum must fit a word.
    function groupSum(bytes32[] memory keys, uint256[] memory values) internal pure {
        uint256 n = keys.length;
        if (values.length != n) n = _outOfBounds();
        if (n < 2) return;
        for (uint256 i = 1; i < n; ++i) {
            bytes32 key = keys[i];
            uint256 value = values[i];
            uint256 j = i;
            while (j != 0 && keys[j - 1] > key) {
                keys[j] = keys[j - 1];
                values[j] = values[j - 1];
                --j;
            }
            keys[j] = key;
            values[j] = value;
        }
        uint256 kept = 0;
        uint256 sum = values[0];
        for (uint256 i = 1; i < n; ++i) {
            if (keys[i] == keys[kept]) {
                sum += values[i];
            } else {
                values[kept] = sum;
                keys[++kept] = keys[i];
                sum = values[i];
            }
        }
        values[kept] = sum;
        Arrays.truncate(keys, kept + 1);
        Arrays.truncate(values, kept + 1);
    }

    /// @dev Raises the `Panic(0x32)` an out-of-range index raises, which is the
    /// portable spelling of a failed range check.
    function _outOfBounds() private pure returns (uint256) {
        return new uint256[](0)[0];
    }
}
