//! Direct MIR instruction to EVM opcode mapping.

use super::op;
use crate::mir::InstKind;

/// Returns the EVM opcode that directly implements a MIR instruction.
pub(super) const fn mir_opcode(kind: &InstKind) -> Option<u8> {
    Some(match kind {
        InstKind::Add(..) => op::ADD,
        InstKind::Sub(..) => op::SUB,
        InstKind::Mul(..) => op::MUL,
        InstKind::Div(..) => op::DIV,
        InstKind::SDiv(..) => op::SDIV,
        InstKind::Mod(..) => op::MOD,
        InstKind::SMod(..) => op::SMOD,
        InstKind::Exp(..) => op::EXP,
        InstKind::AddMod(..) => op::ADDMOD,
        InstKind::MulMod(..) => op::MULMOD,
        InstKind::And(..) => op::AND,
        InstKind::Or(..) => op::OR,
        InstKind::Xor(..) => op::XOR,
        InstKind::Not(..) => op::NOT,
        InstKind::Clz(..) => op::CLZ,
        InstKind::Shl(..) => op::SHL,
        InstKind::Shr(..) => op::SHR,
        InstKind::Sar(..) => op::SAR,
        InstKind::Byte(..) => op::BYTE,
        InstKind::Lt(..) => op::LT,
        InstKind::Gt(..) => op::GT,
        InstKind::SLt(..) => op::SLT,
        InstKind::SGt(..) => op::SGT,
        InstKind::Eq(..) => op::EQ,
        InstKind::IsZero(..) => op::ISZERO,
        InstKind::MLoad(..) => op::MLOAD,
        InstKind::MStore(..) => op::MSTORE,
        InstKind::MStore8(..) => op::MSTORE8,
        InstKind::MSize => op::MSIZE,
        InstKind::SLoad(..) => op::SLOAD,
        InstKind::SStore(..) => op::SSTORE,
        InstKind::TLoad(..) => op::TLOAD,
        InstKind::TStore(..) => op::TSTORE,
        InstKind::CalldataLoad(..) => op::CALLDATALOAD,
        InstKind::CalldataSize => op::CALLDATASIZE,
        InstKind::Keccak256(..) => op::KECCAK256,
        InstKind::Caller => op::CALLER,
        InstKind::CallValue => op::CALLVALUE,
        InstKind::Address => op::ADDRESS,
        InstKind::Origin => op::ORIGIN,
        InstKind::GasPrice => op::GASPRICE,
        InstKind::Gas => op::GAS,
        InstKind::Timestamp => op::TIMESTAMP,
        InstKind::BlockNumber => op::NUMBER,
        InstKind::Coinbase => op::COINBASE,
        InstKind::ChainId => op::CHAINID,
        InstKind::SelfBalance => op::SELFBALANCE,
        InstKind::BaseFee => op::BASEFEE,
        InstKind::BlobBaseFee => op::BLOBBASEFEE,
        InstKind::GasLimit => op::GASLIMIT,
        InstKind::SlotNum => op::SLOTNUM,
        InstKind::PrevRandao => op::PREVRANDAO,
        InstKind::Balance(..) => op::BALANCE,
        InstKind::BlockHash(..) => op::BLOCKHASH,
        InstKind::BlobHash(..) => op::BLOBHASH,
        InstKind::ExtCodeSize(..) => op::EXTCODESIZE,
        InstKind::ExtCodeHash(..) => op::EXTCODEHASH,
        InstKind::CodeSize => op::CODESIZE,
        InstKind::ReturnDataSize => op::RETURNDATASIZE,
        InstKind::SignExtend(..) => op::SIGNEXTEND,
        InstKind::Create(..) => op::CREATE,
        InstKind::Create2(..) => op::CREATE2,
        _ => return None,
    })
}
