//@ check-pass
contract C {
    function f() public returns (uint256 x) {
        assembly {
            stop()
            invalid()
            pop(sdiv(6, 2))
            pop(smod(7, 3))
            pop(lt(1, 2))
            pop(gt(2, 1))
            pop(slt(1, 2))
            pop(sgt(2, 1))
            pop(eq(1, 1))
            pop(iszero(0))
            pop(byte(0, 0xff))
            pop(clz(0))
            pop(addmod(1, 2, 3))
            pop(mulmod(1, 2, 3))
            pop(signextend(0, 0xff))
            pop(keccak256(0, 0))
            pop(address())
            pop(balance(0))
            pop(selfbalance())
            pop(caller())
            pop(callvalue())
            pop(calldataload(0))
            pop(calldatasize())
            calldatacopy(0, 0, 0)
            pop(codesize())
            codecopy(0, 0, 0)
            pop(extcodesize(0))
            extcodecopy(0, 0, 0, 0)
            pop(returndatasize())
            returndatacopy(0, 0, 0)
            pop(extcodehash(0))
            pop(mload(0))
            mstore(0, 1)
            mstore8(0, 1)
            pop(sload(0))
            sstore(0, 1)
            pop(tload(0))
            tstore(0, 1)
            pop(msize())
            pop(gas())
            log0(0, 0)
            log1(0, 0, 1)
            log2(0, 0, 1, 2)
            log3(0, 0, 1, 2, 3)
            log4(0, 0, 1, 2, 3, 4)
            pop(create(0, 0, 0))
            pop(create2(0, 0, 0, 0))
            pop(call(gas(), 0, 0, 0, 0, 0, 0))
            pop(callcode(gas(), 0, 0, 0, 0, 0, 0))
            pop(delegatecall(gas(), 0, 0, 0, 0, 0))
            pop(staticcall(gas(), 0, 0, 0, 0, 0))
            pop(extcall(0, 0, 0, 0))
            pop(extdelegatecall(0, 0, 0))
            pop(extstaticcall(0, 0, 0))
            return(0, 0)
            revert(0, 0)
            selfdestruct(0)
            pop(chainid())
            pop(basefee())
            pop(blobbasefee())
            pop(blobhash(0))
            pop(coinbase())
            pop(difficulty())
            pop(prevrandao())
            pop(gaslimit())
            pop(number())
            pop(timestamp())
            pop(gasprice())
            pop(origin())
            pop(blockhash(0))
            mcopy(0, 0, 0)
            x := 1
        }
    }
}
