name: Deny

on:
  push:
    branches: [main]
    paths: [deny.toml, Cargo.lock]
  pull_request:
    branches: [main]
    paths: [deny.toml, Cargo.lock]
  workflow_dispatch:
    # Needed so we can run it manually

jobs:
  cargo-deny:
    name: cargo deny check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check all
