name: Scan GitHub Actions

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@2dd4664cc3b3eb8809d0339fd9ed98106f8ed24f # refs/pull/266/head
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      ensure-secure-runner: false
