name: Scan GitHub Actions

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@8bef8f477c4d4e0fb45c1770ff49dfb3a27c5e57 # 2026-09-27T07-47-26Z-8bef8f47
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      ensure-secure-runner: false
