name: Scan GitHub Actions

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@2266f708a378d7e72378413158112fcafadb1a50 # pr-294-warning-rollout
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      secure-runner-warning-annotations: false
      secure-runner-fail-on-violation: false
