name: Website

permissions: {}

on:
  push:
    branches: [main]
    paths:
      - web/**
      - .github/workflows/web-pages.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: voidzero-dev/setup-vp@0cffb0a1ac50daa1541b57d1eb7c843f479522e1 # v1.18.0
        with:
          cache: true
          node-version: '24'
          working-directory: web
      - name: Check website
        working-directory: web
        run: vp check
      - name: Test website
        working-directory: web
        run: vp test --run
      - name: Check website Worker
        working-directory: web
        run: vp run worker:check
      - name: Build website
        working-directory: web
        run: vp build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: web/dist
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
